# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmarket', models.CharField(max_length=14, verbose_name='market')),
                ('ccountry', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='country')),
                ('clanguages', models.CharField(max_length=28, verbose_name='languages')),
            ],
            options={
                'ordering': ('cmarket',),
                'verbose_name_plural': 'markets',
                'db_table': 'markets',
            },
        ),
    ]
