# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='iebaysiteid',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='global ID'),
        ),
    ]
