# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_market_iebaysiteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='cmarket',
            field=models.CharField(max_length=14, unique=True, verbose_name='market'),
        ),
        migrations.AlterField(
            model_name='market',
            name='iebaysiteid',
            field=models.PositiveSmallIntegerField(default=1000, unique=True, verbose_name='global ID'),
        ),
    ]
