# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_auto_20171215_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='clanguages',
        ),
        migrations.AddField(
            model_name='market',
            name='clanguage',
            field=models.CharField(default='en-US', max_length=8, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='market',
            name='ccountry',
            field=django_countries.fields.CountryField(default='US', max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='market',
            name='iebaysiteid',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='global ID'),
        ),
    ]
