# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_auto_20171215_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='ccountry',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='market',
            name='clanguage',
            field=models.CharField(max_length=8, verbose_name='language'),
        ),
    ]
