# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20171215_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='icategoryver',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='most recent category version'),
        ),
    ]
