# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_market_icategoryver'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='ccurrencydef',
            field=models.CharField(max_length=3, null=True, verbose_name='currency default'),
        ),
    ]
