# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_market_ccurrencydef'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='bhascategories',
            field=models.NullBooleanField(verbose_name='has own categories?'),
        ),
    ]
