# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_market_bhascategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='cmarket',
            field=models.CharField(max_length=14, unique=True, verbose_name='ebay Global ID'),
        ),
        migrations.AlterField(
            model_name='market',
            name='iebaysiteid',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='site ID'),
        ),
    ]
