# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_auto_20171217_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ('cMarket',), 'verbose_name_plural': 'markets'},
        ),
        migrations.RenameField(
            model_name='market',
            old_name='bhascategories',
            new_name='bHasCategories',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='ccountry',
            new_name='cCountry',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='ccurrencydef',
            new_name='cCurrencyDef',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='clanguage',
            new_name='cLanguage',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='cmarket',
            new_name='cMarket',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='icategoryver',
            new_name='iCategoryVer',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='iebaysiteid',
            new_name='iEbaySiteID',
        ),
    ]
