# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 05:49
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_auto_20171219_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='cCurrencyDef',
            field=core.models.UpperCaseCharField(max_length=3, null=True, verbose_name='currency default'),
        ),
    ]
