# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 06:19
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_auto_20171220_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='cMarket',
            field=core.models.UpperCaseCharField(max_length=14, unique=True, verbose_name='ebay Global ID'),
        ),
    ]
