# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 13:26
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0006_auto_20171114_1537'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(db_index=True, max_length=48, verbose_name='model number or name')),
                ('ckeywords', models.CharField(max_length=88, verbose_name='model key words')),
                ('bkeywordrequired', models.BooleanField(default=True, verbose_name='key word required?')),
                ('bsplitdigitsok', models.BooleanField(default=False, verbose_name='split digits OK?')),
                ('istars', core.models.IntegerRangeField(verbose_name='desireability, 10 star model is most desireable')),
                ('bgenericmodel', models.BooleanField(default=True, verbose_name='generic model?')),
                ('bsubmodelsok', models.BooleanField(default=True, verbose_name='want to get sub models?')),
                ('bmusthavebrand', models.BooleanField(default=False, verbose_name='must have brand key words?')),
                ('bwanted', models.BooleanField(default=True, verbose_name='want this model?')),
                ('bgetpictures', models.BooleanField(default=True, verbose_name='want to download pics?')),
                ('bgetdescription', models.BooleanField(default=True, verbose_name='want the description text?')),
                ('ccomment', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('ilegacykey', models.PositiveIntegerField(unique=True, verbose_name='legacy key')),
                ('tlegacycreate', models.DateTimeField(verbose_name='legacy row created on')),
                ('tlegacymodify', models.DateTimeField(blank=True, verbose_name='legacy row updated on')),
                ('tcreate', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('tmodify', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('ibrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.Brand')),
                ('icategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('iuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'models',
                'ordering': ('ctitle',),
                'verbose_name_plural': 'models',
            },
        ),
    ]
