# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='bSubModelsOK',
            field=models.BooleanField(default=False, help_text='Applies when the model name/number ends with a letter or number that varies.  If you want to track submodels separately, do not check this and enter a separate model record for each submodel.  Note that if the model number is 515b and the box is checked, bot will find both 515a and 515.  Note this option only applies to the model number or name above, NOT to lines under "Considered a hit if this text is found (optional)"', verbose_name='include sub models (suffix such as A, B, C, etc.)?'),
        ),
    ]
