# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='tlegacymodify',
            field=models.DateTimeField(blank=True, null=True, verbose_name='legacy row updated on'),
        ),
    ]
