# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20171118_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='ibrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand'),
        ),
    ]
