# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-26 21:18
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20191201_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='bSubModelsOK',
            field=models.BooleanField(default=False, help_text='Applies when the model name/number ends with a letter or number that varies.  If you want to track submodels separately, do not check this and enter a separate model record for each submodel.  Note that if the model number is 515b and the box is checked, bot will find both 515a and 515.  Also note this option only applies to the model number or name above, NOT to lines under "Considered a hit if this text is found ..." below.', verbose_name='include sub models (suffix such as A, B, C, etc.)?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Put nick names, common misspellings and alternate model numbers or names here -- leave blank if Bot only needs to look for the model number or name.<br>Each line is evaluated separately, Bot will know item is in this model if any one line matches.<br/>Bot expands hyphens, spaces and number/letter boundaries,<br/>"208A" will find 208A, 208 A and 208-A<br/>"208 A" will find 208A, 208 A and 208-A<br/>"208-A" will find 208A, 208 A and 208-A', null=True, verbose_name='Considered a hit if this text is found (optional -- if you include, bot will also search for this)'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cTitle',
            field=core.models.gotSomethingOutsideTitleParensCharField(db_index=True, help_text='Put the model number or name here -- Bot will search for this in the auction title for each item found.<br/>Optionally, you can put additional description in parentheses ().  While searching auction titles, bot will ignore anything in parentheses.<br/>Bot expands hyphens, spaces and number/letter boundaries,<br/>"208A" will find 208A, 208 A and 208-A<br/>"208 A" will find 208A, 208 A and 208-A<br/>"208-A" will find 208A, 208 A and 208-A', max_length=48, verbose_name='model number or name'),
        ),
    ]
