# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 05:52
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20171118_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='istars',
            field=core.models.IntegerRangeField(default=5, verbose_name='desireability, 10 star model is most desireable'),
        ),
    ]
