# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0004_auto_20171122_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfilespec', models.FilePathField(verbose_name='file path & name for model picture')),
                ('tcreate', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('tmodify', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('imodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Model')),
                ('iuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modelpics',
                'verbose_name_plural': 'modelpics',
            },
        ),
    ]
