# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_modelpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpic',
            name='imodel',
        ),
        migrations.RemoveField(
            model_name='modelpic',
            name='iuser',
        ),
        migrations.AddField(
            model_name='model',
            name='cexcludeif',
            field=models.TextField(blank=True, null=True, verbose_name='not a hit if this text is found'),
        ),
        migrations.AddField(
            model_name='model',
            name='cfile1spec',
            field=models.FilePathField(blank=True, null=True, verbose_name='file path & name for model picture 1'),
        ),
        migrations.AddField(
            model_name='model',
            name='cfile2spec',
            field=models.FilePathField(blank=True, null=True, verbose_name='file path & name for model picture 2'),
        ),
        migrations.AddField(
            model_name='model',
            name='cfile3spec',
            field=models.FilePathField(blank=True, null=True, verbose_name='file path & name for model picture 3'),
        ),
        migrations.AddField(
            model_name='model',
            name='cfile4spec',
            field=models.FilePathField(blank=True, null=True, verbose_name='file path & name for model picture 4'),
        ),
        migrations.AddField(
            model_name='model',
            name='cfile5spec',
            field=models.FilePathField(blank=True, null=True, verbose_name='file path & name for model picture 5'),
        ),
        migrations.AlterField(
            model_name='model',
            name='bmusthavebrand',
            field=models.BooleanField(default=False, verbose_name='must have brand in aution title?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='bsubmodelsok',
            field=models.BooleanField(default=True, verbose_name='include sub models (suffix such as A, B, C, etc.)?'),
        ),
        migrations.DeleteModel(
            name='ModelPic',
        ),
    ]
