# Generated by Django 3.2.4 on 2021-08-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20200410_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='iModelYear',
            field=models.IntegerField(blank=True, help_text='optional - can specify if model varies by year', null=True, verbose_name='model year'),
        ),
    ]
