# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20171129_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='cfile1spec',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='file path & name for model picture 1'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cfile2spec',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='file path & name for model picture 2'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cfile3spec',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='file path & name for model picture 3'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cfile4spec',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='file path & name for model picture 4'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cfile5spec',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='file path & name for model picture 5'),
        ),
    ]
