# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20171203_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='ibrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='model',
            name='icategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='model',
            name='iuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
