# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_model_clookfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='cKeyWords',
            field=models.CharField(blank=True, max_length=88, null=True, verbose_name='model key words'),
        ),
    ]
