# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 03:26
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20180106_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='bGenericModel',
            field=models.BooleanField(default=True, help_text='model name/number is used by more than one brand', verbose_name='generic model?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='bGetDescription',
            field=models.BooleanField(default=True, help_text='Bot will download full descriptions only if you do want them', verbose_name='want the description text?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='bGetPictures',
            field=models.BooleanField(default=True, help_text='Bot will download pictures only if you want them', verbose_name='want to download pics?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='bKeyWordRequired',
            field=models.BooleanField(default=True, help_text='Bot will know this model is for sale only if these key words are in the description', verbose_name='key word required?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='bMustHaveBrand',
            field=models.BooleanField(default=False, help_text='Bot will know item for sale is this model only if Brand name is in the auction title (useful when model name/number is common (example: Model T Ford; "T" is common)', verbose_name='must have brand in aution title?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='bSubModelsOK',
            field=models.BooleanField(default=True, help_text='Set to False when you want to track the submodels separately (so you should enter a model record for each submodel)', verbose_name='include sub models (suffix such as A, B, C, etc.)?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='bWanted',
            field=models.BooleanField(default=True, help_text='Bot will download full descriptions and pictures only if you do want to track this model', verbose_name='want this model?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='bsplitdigitsok',
            field=models.BooleanField(default=False, help_text='Bot will know this model is for sale whether the hyphens are in the model number/name or not', verbose_name='split digits OK?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cExcludeIf',
            field=models.TextField(blank=True, help_text='Not a hit if this text is found (each line evaluated separately, put different exclude tests on different lines)', null=True, verbose_name='Not a hit if this text is found'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cKeyWords',
            field=models.CharField(blank=True, help_text='Bot will look for this text in the item description', max_length=88, null=True, verbose_name='model key words'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Considered a hit if this text is found -- each line evaluated separately, put different look for tests on different lines', null=True, verbose_name='Considered a hit if this text is found'),
        ),
        migrations.AlterField(
            model_name='model',
            name='iStars',
            field=core.models.IntegerRangeField(default=5, help_text='Bot considers when deciding whether to download full description and pictures', verbose_name='desireability, 10 star model is most desireable'),
        ),
    ]
