# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20180116_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='iLegacyKey',
            field=models.PositiveIntegerField(null=True, verbose_name='legacy key'),
        ),
    ]
