# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20180119_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='bGenericModel',
            field=models.BooleanField(default=False, help_text='model name/number is used by more than one brand', verbose_name='generic model?'),
        ),
        migrations.AlterField(
            model_name='model',
            name='bKeyWordRequired',
            field=models.BooleanField(default=False, help_text='Bot will know this model is for sale only if these key words are in the description', verbose_name='key word required?'),
        ),
    ]
