# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_auto_20180127_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='oRegEx',
            new_name='oRegExFound',
        ),
    ]
