# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 15:08
from __future__ import unicode_literals

from django.db import migrations
import regex_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_auto_20180127_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='oRegExExclude',
            field=regex_field.fields.RegexField(max_length=128, null=True),
        ),
    ]
