# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_model_oregexexclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='cKeyWords',
            field=models.TextField(blank=True, help_text='Words that must be found in the title <em>IN ADDITION TO</em> model name/#.Put alternate key words on separate lines -- Bot will know item is for this model if words on any one line match.', null=True, verbose_name='model key words (optional)'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Leave blank if bot only needs to look for the model name/number. Each line evaluated separately, put common misspellings and alternate names here.', null=True, verbose_name='Considered a hit if this text is found (optional)'),
        ),
        migrations.AlterField(
            model_name='model',
            name='cTitle',
            field=models.CharField(db_index=True, help_text='while searching auction titles, bot will ignore anything in parentheses ()', max_length=48, verbose_name='model number or name'),
        ),
    ]
