# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_auto_20180128_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='bKeyWordRequired',
        ),
    ]
