# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_auto_20180128_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='bSplitDigitsOK',
        ),
    ]
