# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_remove_model_bsplitdigitsok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='oRegExFound',
            new_name='oRegExLook4Title',
        ),
    ]
