# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0033_auto_20180324_1741'),
        ('brands', '0021_auto_20180324_1741'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0031_auto_20180320_1126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([('cTitle', 'iBrand', 'iCategory', 'iUser')]),
        ),
    ]
