# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0032_auto_20180324_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='bSubModelsOK',
            field=models.BooleanField(default=False, help_text='Set to False when you want to track the submodels separately (so you should enter a model record for each submodel)', verbose_name='include sub models (suffix such as A, B, C, etc.)?'),
        ),
    ]
