# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemhits', '0002_auto_20171205_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemhit',
            old_name='iitemnumb',
            new_name='iItemNumb',
        ),
    ]
