# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemhits', '0003_auto_20171219_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemhit',
            old_name='ctitle',
            new_name='cTitle',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='inumberofbids',
            new_name='iBidCount',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='ibrand',
            new_name='iBrand',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='icategory',
            new_name='iCategory',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='iuser',
            new_name='iUser',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='mbuyitnow',
            new_name='mBuyItNow',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='mbuyitnow_currency',
            new_name='mBuyItNow_currency',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='mlastbid',
            new_name='mLastBid',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='mlastbid_currency',
            new_name='mLastBid_currency',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='tauctionbeg',
            new_name='tAuctionBeg',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='tauctionend',
            new_name='tAuctionEnd',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='tcreate',
            new_name='tCreate',
        ),
        migrations.RenameField(
            model_name='itemhit',
            old_name='tmodify',
            new_name='tModify',
        ),
    ]
