# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemhits', '0005_auto_20171219_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isequence', models.PositiveSmallIntegerField(verbose_name='sequence')),
                ('cfilename', models.CharField(max_length=28, verbose_name='local file name')),
                ('coriginalurl', models.TextField(verbose_name='original URL')),
                ('tCreate', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('iItemNumb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemhits.ItemHit')),
                ('iUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'db_table': 'itemimages',
                'verbose_name_plural': 'itemimages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemimage',
            unique_together=set([('iItemNumb', 'isequence')]),
        ),
    ]
