# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemhits', '0006_auto_20180130_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhit',
            name='iBrand',
        ),
        migrations.RemoveField(
            model_name='itemhit',
            name='iCategory',
        ),
        migrations.RemoveField(
            model_name='itemhit',
            name='iModel',
        ),
        migrations.RemoveField(
            model_name='itemhit',
            name='iUser',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='iItemNumb',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ebay item number'),
        ),
        migrations.DeleteModel(
            name='ItemHit',
        ),
    ]
