# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='tlegacymodify',
            field=models.DateTimeField(null=True, verbose_name='legacy row updated on'),
        ),
    ]
