# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 05:52
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cexcludeif',
            field=models.TextField(blank=True, null=True, verbose_name='exclude item when this text is found'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='ilegacykey',
            field=models.PositiveIntegerField(null=True, verbose_name='legacy key'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='istars',
            field=core.models.IntegerRangeField(default=5, verbose_name='desireability, 10 star brand is most desireable'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tlegacycreate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='legacy row created on'),
        ),
    ]
