# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20171104_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('ctitle',), 'verbose_name_plural': 'brands'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='cbrandname',
            new_name='ctitle',
        ),
    ]
