# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 06:09
from __future__ import unicode_literals

import brands.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20171104_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='istars',
            field=brands.models.IntegerRangeField(verbose_name='desireability, 10 star brand is most desireable'),
        ),
    ]
