# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_auto_20171129_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='iuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
