# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_brand_ckeywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cRegExKeyWords',
            field=models.TextField(null=True),
        ),
    ]
