# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_auto_20171205_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('cTitle',), 'verbose_name_plural': 'brands'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='ballofinterest',
            new_name='bAllOfInterest',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='bwanted',
            new_name='bWanted',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='ccomment',
            new_name='cComment',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='cexcludeif',
            new_name='cExcludeIf',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='cnationality',
            new_name='cNationality',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='ctitle',
            new_name='cTitle',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='ilegacykey',
            new_name='iLegacyKey',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='istars',
            new_name='iStars',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='iuser',
            new_name='iUser',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='tcreate',
            new_name='tCreate',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='tlegacycreate',
            new_name='tLegacyCreate',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='tlegacymodify',
            new_name='tLegacyModify',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='tmodify',
            new_name='tModify',
        ),
    ]
