# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-06 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_brand_cregexkeywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cKeyWords',
            field=models.TextField(blank=True, help_text='Putting text here is optional, but if there is text here, robot will consider it REQUIRED -- must be found in the title <b>IN ADDITION TO</b> brand name.<br>Put alternate key words on separate lines -- Bot will know item is for this brand if words on any one line match.', null=True, verbose_name='brand key words'),
        ),
    ]
