# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_auto_20171219_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cLookFor',
            field=models.TextField(blank=True, null=True, verbose_name='Considered a hit if this text is found (each line evaluated separately, put different look for tests on different lines)'),
        ),
    ]
