# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_brand_clookfor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('cTitle',), 'verbose_name': 'brand name', 'verbose_name_plural': 'brands'},
        ),
    ]
