# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_auto_20180126_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='oRegEx',
            new_name='oRegExFound',
        ),
    ]
