# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0012_brand_oregexexclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Leave blank if bot only needs to look for the brand name. Each line evaluated separately, put common misspellings and alternate names here.', null=True, verbose_name='Considered a hit if this text is found (optional)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cTitle',
            field=models.CharField(db_index=True, help_text='while searching auction titles, bot will ignore anything in parentheses ()', max_length=48, verbose_name='brand name'),
        ),
    ]
