# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0013_auto_20180128_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cExcludeIf',
            field=models.TextField(blank=True, help_text='Bot will know item is <b>NOT</b> of this brand if any one line matches (each line evaluated separately, put different exclude tests on different lines)', null=True, verbose_name='Not a hit if this text is found (optional)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Put common misspellings and alternate names here -- leave blank if bot only needs to look for the brand name. Each line evaluated separately, Bot will know item is of this brand if any one line matches.', null=True, verbose_name='Considered a hit if this text is found (optional)'),
        ),
    ]
