# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0014_auto_20180128_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='oRegExFound',
            new_name='oRegExLook4Title',
        ),
    ]
