# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0015_auto_20180130_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Put nick names, common misspellings and alternate brand names here -- leave blank if Bot only needs to look for the brand name.<br>Each line is evaluated separately, Bot will know item is in this brand if any one line matches.', null=True, verbose_name='Considered a hit if this text is found (optional)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cNationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cTitle',
            field=models.CharField(db_index=True, help_text='Put the brand name here -- Bot will search for this in the auction titles.<br/>Optionally, you can put additional description in parentheses ().  While searching auction titles, bot will ignore anything in parentheses.', max_length=48, verbose_name='brand name'),
        ),
    ]
