# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0016_auto_20180214_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='oRegExExclude',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='oRegExLook4Title',
        ),
        migrations.AddField(
            model_name='brand',
            name='sRegExExclude',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='sRegExLook4Title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
