# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0018_auto_20180319_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='sRegExLook4Title',
            field=models.TextField(null=True),
        ),
    ]
