# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0020_auto_20180320_1126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set([('cTitle', 'iUser')]),
        ),
    ]
