# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='iItemNumb',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='item number'),
        ),
        migrations.AlterField(
            model_name='useritemfound',
            name='iItemNumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finders.ItemFound'),
        ),
    ]
