# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='iItemNumb',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='item number'),
        ),
        migrations.AlterField(
            model_name='useritemfound',
            name='iItemNumb',
            field=models.BigIntegerField(verbose_name='item number'),
        ),
    ]
