# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0003_auto_20190620_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritemfound',
            name='tGotPics',
        ),
    ]
