# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0005_useritemfound_tputinkeepers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='tTimeEnd',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='ending date/time'),
        ),
    ]
