# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0006_auto_20190823_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritemfound',
            name='tTimeEnd',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='ending date/time'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='tTimeEnd',
            field=models.DateTimeField(null=True, verbose_name='ending date/time'),
        ),
    ]
