# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-31 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0007_auto_20190824_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='i2ndCatHeirarchy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary_category', to='ebayinfo.CategoryHierarchy', verbose_name='category hierarchy (secondary)'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iCatHeirarchy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary_category', to='ebayinfo.CategoryHierarchy', verbose_name='category hierarchy (primary)'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iCategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ebay_primary_category', to='ebayinfo.EbayCategory', verbose_name='primary category ID'),
        ),
    ]
