# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-03 12:02
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finders', '0008_auto_20190831_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iMaxStars', core.models.IntegerRangeField(default=0, null=True, verbose_name='hit stars')),
                ('bListExclude', models.BooleanField(default=False, verbose_name='exclude from listing?')),
                ('iItemNumb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finders.ItemFound')),
                ('iUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name_plural': 'userfinders',
                'db_table': 'userfinders',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfinder',
            unique_together=set([('iItemNumb', 'iUser')]),
        ),
    ]
