# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0011_auto_20191103_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinder',
            name='cListingType',
            field=models.CharField(max_length=15, null=True, verbose_name='listing type'),
        ),
        migrations.AddField(
            model_name='userfinder',
            name='cMarket',
            field=models.CharField(max_length=14, null=True, verbose_name='market Global ID'),
        ),
        migrations.AddField(
            model_name='userfinder',
            name='cTitle',
            field=models.CharField(max_length=80, null=True, verbose_name='item title'),
        ),
        migrations.AddField(
            model_name='userfinder',
            name='tTimeEnd',
            field=models.DateTimeField(null=True, verbose_name='ending date/time'),
        ),
    ]
