# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-17 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0015_itemfound_ihanglingtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemfound',
            old_name='iHanglingTime',
            new_name='iHandlingTime',
        ),
    ]
