# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-01 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0018_itemfoundtemp_ctitleleftover'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinder',
            name='iMaxModel',
            field=models.IntegerField(default=False, null=True, verbose_name='model hit with most stars'),
        ),
    ]
