# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-18 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0019_userfinder_imaxmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinder',
            name='iItemNumb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finders.ItemFound', verbose_name='eBay Item Number'),
        ),
    ]
