# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-26 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0020_auto_20191218_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfinder',
            old_name='iMaxStars',
            new_name='iHitStars',
        ),
    ]
