# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-05 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0005_brand_cregexkeywords'),
        ('categories', '0005_auto_20200104_2144'),
        ('models', '0004_auto_20191226_2118'),
        ('finders', '0022_auto_20191226_2123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useritemfound',
            unique_together=set([('iItemNumb', 'iUser', 'iModel', 'iBrand', 'iCategory')]),
        ),
    ]
