# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-06 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0023_auto_20200105_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfoundtemp',
            name='cFoundModel',
            field=models.CharField(max_length=48, null=True, verbose_name='model name/number found in auction title'),
        ),
        migrations.AlterField(
            model_name='itemfoundtemp',
            name='cModelAlphaNum',
            field=models.CharField(max_length=48, null=True, verbose_name='model name/number alpha num only'),
        ),
    ]
