# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-15 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0024_auto_20200306_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfinder',
            old_name='bGetPictures',
            new_name='bGetResults',
        ),
    ]
