# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-15 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0025_auto_20200315_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritemfound',
            old_name='bGetPictures',
            new_name='bGetResults',
        ),
    ]
