# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-15 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0026_auto_20200315_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinder',
            name='bGetResults',
            field=models.NullBooleanField(default=False, verbose_name='get results?'),
        ),
        migrations.AlterField(
            model_name='useritemfound',
            name='bGetResults',
            field=models.BooleanField(default=False, verbose_name='get results?'),
        ),
    ]
