# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-24 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0027_auto_20200315_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinder',
            name='cLookFor',
            field=models.TextField(blank=True, null=True, verbose_name='dummy for search compatibility'),
        ),
    ]
