# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-28 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0028_userfinder_clookfor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfinder',
            old_name='bGetResults',
            new_name='bGetResult',
        ),
        migrations.RenameField(
            model_name='useritemfound',
            old_name='bGetResults',
            new_name='bGetResult',
        ),
    ]
