# Generated by Django 2.2.10 on 2020-06-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0030_auto_20200503_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfoundtemp',
            name='bModelKeyWords',
            field=models.NullBooleanField(default=False, verbose_name='model has key words and they are in auction title?'),
        ),
    ]
