# Generated by Django 2.2.13 on 2020-07-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0032_auto_20200705_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfoundtemp',
            name='bIncludeThis',
            field=models.BooleanField(default=True, verbose_name='include this hit when populating table?'),
        ),
    ]
