# Generated by Django 2.2.13 on 2020-07-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0033_itemfoundtemp_bincludethis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemFoundTemp',
        ),
    ]
