# Generated by Django 3.1.4 on 2020-12-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0034_delete_itemfoundtemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinder',
            name='bGetResult',
            field=models.BooleanField(default=False, null=True, verbose_name='get results?'),
        ),
        migrations.AlterField(
            model_name='userfinder',
            name='bListExclude',
            field=models.BooleanField(default=False, null=True, verbose_name='exclude from listing?'),
        ),
    ]
