# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='cLastResult',
            field=models.CharField(max_length=28, null=True, verbose_name='last search outcome'),
        ),
        migrations.AddField(
            model_name='search',
            name='cPriority',
            field=models.CharField(max_length=2, null=True, verbose_name='processing priority'),
        ),
        migrations.AddField(
            model_name='search',
            name='cTitle',
            field=models.CharField(max_length=28, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='search',
            name='tLastSearch',
            field=models.DateTimeField(null=True, verbose_name='last search'),
        ),
    ]
