# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 08:20
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iConditionID', models.PositiveSmallIntegerField(verbose_name='ebay condition ID')),
                ('cTitle', models.CharField(max_length=24, verbose_name='ebay condition description')),
            ],
            options={
                'verbose_name_plural': 'ebay condition descriptions',
                'db_table': 'conditions',
            },
        ),
        migrations.CreateModel(
            name='EbayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iCategoryID', models.PositiveIntegerField(db_index=True, verbose_name='ebay category number')),
                ('name', models.CharField(max_length=50, verbose_name='ebay category description')),
                ('iLevel', models.PositiveSmallIntegerField(verbose_name='ebay level (top is 1, lower levels are bigger numbers)')),
                ('iParentID', models.PositiveIntegerField(verbose_name='ebay parent category')),
                ('bLeafCategory', models.BooleanField(verbose_name='leaf category?')),
                ('iTreeVersion', models.PositiveSmallIntegerField(verbose_name='category tree version')),
                ('iMarket', models.PositiveIntegerField(db_index=True, verbose_name='ebay market')),
                ('iSupercededBy', models.PositiveIntegerField(null=True, verbose_name='superceded by this ebay category')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ebayinfo.EbayCategory')),
            ],
            options={
                'verbose_name_plural': 'ebay categories',
                'db_table': 'ebay_categories',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cMarket', core.models.UpperCaseCharField(max_length=14, unique=True, verbose_name='ebay Global ID')),
                ('cCountry', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('cLanguage', models.CharField(max_length=8, verbose_name='language')),
                ('iEbaySiteID', models.PositiveSmallIntegerField(unique=True, verbose_name='site ID')),
                ('bHasCategories', models.NullBooleanField(verbose_name='has own categories?')),
                ('iCategoryVer', models.PositiveSmallIntegerField(null=True, verbose_name='most recent category version')),
                ('cCurrencyDef', core.models.UpperCaseCharField(max_length=3, null=True, verbose_name='currency default')),
            ],
            options={
                'ordering': ('cMarket',),
                'verbose_name_plural': 'markets',
                'db_table': 'markets',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ebaycategory',
            unique_together=set([('iCategoryID', 'iMarket')]),
        ),
    ]
