# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaycategory',
            name='iMarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebayinfo.Market', verbose_name='ebay market'),
        ),
    ]
