# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 23:17
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0002_auto_20180218_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='cUseCategoryID',
            field=core.models.UpperCaseCharField(blank=True, max_length=14, null=True, verbose_name='uses category list from this Market'),
        ),
        migrations.AddField(
            model_name='market',
            name='iUtcPlusOrMinus',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='UTC offset'),
        ),
    ]
