# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 12:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0004_auto_20180308_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='iUtcPlusOrMinus',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(-12)], verbose_name='UTC offset'),
        ),
    ]
