# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0005_auto_20180308_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iCategoryID', models.PositiveIntegerField(db_index=True, verbose_name='ebay category number')),
                ('cCatHierarchy', models.TextField(blank=True, null=True, verbose_name='category hierarchy')),
                ('iMarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebayinfo.Market', verbose_name='ebay market')),
            ],
            options={
                'db_table': 'category_hierarchies',
                'verbose_name_plural': 'category hierarchies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoryhierarchy',
            unique_together=set([('iCategoryID', 'iMarket')]),
        ),
    ]
