# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0006_auto_20180311_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryhierarchy',
            options={'ordering': ('iMarket', 'iCategoryID'), 'verbose_name_plural': 'category hierarchies'},
        ),
    ]
