# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0007_auto_20180311_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='id',
        ),
        migrations.AlterField(
            model_name='market',
            name='iEbaySiteID',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='site ID'),
        ),
    ]
