# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0008_auto_20180311_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryhierarchy',
            name='iEbaySiteID',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='ebay market site ID'),
        ),
    ]
