# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0009_categoryhierarchy_iebaysiteid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryhierarchy',
            options={'verbose_name_plural': 'category hierarchies'},
        ),
        migrations.AlterUniqueTogether(
            name='categoryhierarchy',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='categoryhierarchy',
            name='iMarket',
        ),
    ]
