# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0011_auto_20180327_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryhierarchy',
            name='iEbaySiteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebayinfo.Market', verbose_name='ebay market site ID'),
        ),
    ]
