# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0012_auto_20180327_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryhierarchy',
            options={'ordering': ('iEbaySiteID', 'iCategoryID'), 'verbose_name_plural': 'category hierarchies'},
        ),
        migrations.AlterUniqueTogether(
            name='categoryhierarchy',
            unique_together=set([('iCategoryID', 'iEbaySiteID')]),
        ),
    ]
