# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0014_auto_20180327_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaycategory',
            name='name',
            field=models.CharField(max_length=58, verbose_name='ebay category description'),
        ),
    ]
