# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0016_auto_20191103_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaycategory',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='ebaycategory',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='ebaycategory',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
