sExampleErrorNoMoreItem = '''{
    "Version": "1063",
    "Timestamp": "2018-06-03T13:40:05.704Z",
    "Build": "E1063_CORE_APILW_18716243_R1",
    "Ack": "Failure",
    "Errors": [
        {"ShortMessage": "Invalid item ID.",
        "ErrorCode": "10.12",
        "SeverityCode": "Error",
        "ErrorClassification": "RequestError",
        "LongMessage": "Invalid or non-existent item ID."}]}'''

sMissingItemIdErrorGotAck = '''{
    "Version": "1063",
    "Timestamp": "2018-06-03T13:40:05.704Z",
    "Build": "E1063_CORE_APILW_18716243_R1",
    "Ack": "Failure",
    "Errors": [
        {"ShortMessage": "Missing item ID.",
        "ErrorCode": "10.13",
        "SeverityCode": "Error",
        "ErrorClassification": "RequestError",
        "LongMessage": "Missing item ID."}]}'''


sMadeUpErrorNoAck = '''{
    "Version": "1063",
    "Timestamp": "2018-06-03T13:40:05.704Z",
    "Build": "E1063_CORE_APILW_18716243_R1",
    "Ich": "Failure",
    "Errors": [
        {"ShortMessage": "Missing item ID.",
        "ErrorCode": "10.13",
        "SeverityCode": "Error",
        "ErrorClassification": "RequestError",
        "LongMessage": "Missing item ID."}]}'''

# among sResponseItems2Test
s293004871422 = '''{
    "Timestamp":"2019-03-24T02:07:10.877Z",
    "Ack":"Success",
    "Build":"E1089_CORE_APILW_18879361_R1","Version":"1089",
    "Item":{"BestOfferEnabled":true,
        "Description":"One pair gently removed from not great cabinets (see other auction) Le5-5 mods tested and working great with original mounting screws. Sold as is due to age but guaranteed not DOA! Will be packed well Winning buyer must pay within 48 hours Good luck!",
        "ItemID":"293004871422",
        "EndTime":"2019-03-20T02:46:55.000Z",
        "StartTime":"2019-03-13T02:46:55.000Z",
        "ViewItemURLForNaturalSearch":"https://www.ebay.com/itm/Jbl-L65-Jubal-Le5-5-Mids-Pair-Working-Nice-See-Pictures-/293004871422",
        "ListingType":"Chinese",
        "Location":"Woodbury, New Jersey",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"https://thumbs3.ebaystatic.com/pict/2930048714228080_1.jpg",
        "PictureURL":[
            "https://i.ebayimg.com/00/s/NjgwWDEzNDY=/z/9j8AAOSwWbZciG1h/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/ODIxWDE2MDA=/z/KC8AAOSwUf9ciG1x/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/OTQwWDExMDg=/z/LXcAAOSwrn9ciG2V/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/ODk3WDk4Mw==/z/BlEAAOSwDNRciG2N/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/NzY2WDEzMzI=/z/oMUAAOSwJgBciG2~/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/00wAAOSwyAdciG31/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/NzM3WDEzMTU=/z/4OkAAOSw0dFciG3T/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/OTUyWDEwMzE=/z/N08AAOSw7lNciG3l/$_12.JPG?set_id=880000500F"],
        "PostalCode":"08096",
        "PrimaryCategoryID":"50597",
        "PrimaryCategoryName":"Consumer Electronics:Vintage Electronics:Vintage Audio & Video:Vintage Speakers",
        "Quantity":1,
        "Seller":{"UserID":"mleotta1","FeedbackRatingStar":"Turquoise","FeedbackScore":448,"PositiveFeedbackPercent":99.2,"TopRatedSeller":true},
        "BidCount":3,
        "ConvertedCurrentPrice":{"Value":93.0,"CurrencyID":"USD"},"CurrentPrice":{"Value":93.0,"CurrencyID":"USD"},
        "HighBidder":{"UserID":"e***d","FeedbackPrivate":false,"FeedbackRatingStar":"Turquoise","FeedbackScore":175},
        "ListingStatus":"Completed",
        "QuantitySold":1,
        "ShipToLocations":["US","CA","GB","DK","RO","SK","BG","CZ","FI","HU","LV","LT","MT","EE","AU","GR","PT","CY","SI","JP","SE","KR","ID","TW","ZA","TH","BE","FR","HK","IE","NL","PL","ES","IT","DE","AT","BS","IL","MX","NZ","SG","CH","NO","SA","UA","AE","QA","KW","BH","HR","MY","BR","CL","CO","CR","DO","PA","TT","GT","SV","HN","JM","AG","AW","BZ","DM","GD","KN","LC","MS","TC","BB","BD","BM","BN","BO","EC","EG","GF","GG","GI","GP","IS","JE","JO","KH","KY","LI","LK","LU","MC","MO","MQ","MV","NI","OM","PE","PK","PY","RE","VN","UY"],
        "Site":"US",
        "TimeLeft":"PT0S",
        "Title":"Jbl L65 Jubal Le5-5 Mids Pair Working Nice! See Pictures",
        "HitCount":294,
        "PrimaryCategoryIDPath":"293:183077:175740:50597",
        "Country":"US",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted"},
        "MinimumToBid":{"Value":94.0,"CurrencyID":"USD"},"AutoPay":false,
        "PaymentAllowedSite":[],"IntegratedMerchantCreditCardEnabled":false,
        "HandlingTime":3,"GlobalShipping":true,"QuantitySoldByPickupInStore":0,"NewBestOffer":false}}'''

# among sResponseItems2Test
s254154293727 = '''{
    "Timestamp":"2019-03-24T02:17:18.596Z",
    "Ack":"Success",
    "Build":"E1089_CORE_APILW_18879361_R1","Version":"1089",
    "Item":{"BestOfferEnabled":true,
        "Description":"Speakers are fair looking little cosmetic wear They are in working condition. I took front and back pictures.",
        "ItemID":"254154293727",
        "EndTime":"2019-03-14T13:14:25.000Z",
        "StartTime":"2019-03-07T13:14:25.000Z",
        "ViewItemURLForNaturalSearch":"https://www.ebay.com/itm/vintage-klipsch-Lascalas-/254154293727",
        "ListingType":"Chinese",
        "Location":"Sanford, North Carolina",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"https://thumbs4.ebaystatic.com/pict/2541542937278080_1.jpg",
        "PictureURL":[
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/VVoAAOSw-JtceB~p/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/LbIAAOSw~TdceB~r/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/~ksAAOSwp-ZceB~u/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/QUQAAOSwDXFceB~l/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/VDcAAOSwCtJceB~s/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/C9sAAOSw0KdceB~m/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/KYYAAOSwJihceB~i/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/QScAAOSw0IBceB~o/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/dJkAAOSwkCZceB~j/$_12.JPG?set_id=880000500F"],
        "PostalCode":"27332",
        "PrimaryCategoryID":"50597",
        "PrimaryCategoryName":"Consumer Electronics:Vintage Electronics:Vintage Audio & Video:Vintage Speakers",
        "Quantity":1,
        "Seller":{"UserID":"ebpiggie","FeedbackRatingStar":"Turquoise","FeedbackScore":142,"PositiveFeedbackPercent":100.0},
        "BidCount":0,
        "ConvertedCurrentPrice":{"Value":650.0,"CurrencyID":"USD"},"CurrentPrice":{"Value":650.0,"CurrencyID":"USD"},
        "ListingStatus":"Completed",
        "QuantitySold":0,
        "ShipToLocations":["None"],
        "Site":"US",
        "TimeLeft":"PT0S",
        "Title":"vintage klipsch Lascalas",
        "HitCount":116,
        "PrimaryCategoryIDPath":"293:183077:175740:50597",
        "Country":"US",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted"},
        "MinimumToBid":{"Value":650.0,"CurrencyID":"USD"},"AutoPay":false,
        "PaymentAllowedSite":[],"IntegratedMerchantCreditCardEnabled":false,"GlobalShipping":false,"QuantitySoldByPickupInStore":0,"NewBestOffer":false}}'''

# among sResponseItems2Test
s254130264753 = '''{
    "Timestamp":"2019-03-24T02:18:42.807Z",
    "Ack":"Success",
    "Build":"E1089_CORE_APILW_18879361_R1","Version":"1089",
    "Item":{"BestOfferEnabled":true,
        "Description":"",
        "ItemID":"254130264753",
        "EndTime":"2019-02-25T19:34:33.000Z",
        "StartTime":"2019-02-18T19:34:33.000Z",
        "ViewItemURLForNaturalSearch":"https://www.ebay.com/itm/Fisher-105-3-Way-Speakers-Cool-Latticework-Grills-12-Woofers-/254130264753",
        "ListingType":"Chinese",
        "Location":"Berkley, Michigan",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"https://thumbs2.ebaystatic.com/pict/2541302647538080_1.jpg",
        "PictureURL":[
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/qWMAAOSwsftcKmws/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/s0UAAOSwS4VcKmw0/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/92YAAOSwwkRcKmw7/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/cD4AAOSwyApcKmxF/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/3~oAAOSwhEhcKmxK/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/tBsAAOSw5cZcKmxP/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/zfoAAOSwiT1cKmxT/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/CgMAAOSwTQNcKmx9/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/mrUAAOSws2RcKmyV/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/l3IAAOSwWAhcKmyg/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/mqgAAOSwaaNcKmzq/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/7F0AAOSw651cKm0k/$_32.JPG?set_id=880000500F"],
        "PostalCode":"48072",
        "PrimaryCategoryID":"50597",
        "PrimaryCategoryName":"Consumer Electronics:Vintage Electronics:Vintage Audio & Video:Vintage Speakers",
        "Quantity":1,
        "Seller":{"UserID":"jsl001","FeedbackRatingStar":"Turquoise","FeedbackScore":152,"PositiveFeedbackPercent":100.0},
        "BidCount":0,
        "ConvertedCurrentPrice":{"Value":35.0,"CurrencyID":"USD"},"CurrentPrice":{"Value":35.0,"CurrencyID":"USD"},
        "ListingStatus":"Completed",
        "QuantitySold":0,
        "ShipToLocations":["None"],
        "Site":"US",
        "TimeLeft":"PT0S",
        "Title":"The Fisher 105 - 3 Way Speakers \u2013 Cool Latticework Grills - 12\\" Woofers",
        "HitCount":31,
        "PrimaryCategoryIDPath":"293:183077:175740:50597",
        "Country":"US",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted"},
        "MinimumToBid":{"Value":35.0,"CurrencyID":"USD"},"AutoPay":false,
        "PaymentAllowedSite":[],"IntegratedMerchantCreditCardEnabled":false,"GlobalShipping":false,"QuantitySoldByPickupInStore":0,"NewBestOffer":false}}'''

# among sResponseItems2Test
s223348187115 = '''{
    "Timestamp":"2019-03-24T02:20:05.333Z",
    "Ack":"Success",
    "Build":"E1089_CORE_APILW_18879361_R1","Version":"1089",
    "Item":{"BestOfferEnabled":true,
        "Description":"Really nice Vintage Altec Lansing Mahogany Corner Speaker. 15\\" 602A Duplex Driver with the N3000A dividing network. Fully Functioning and sounds fantastic. Gorgeous Ribbon Mahogany Top. The original speaker wire was coiled up inside, and is still attached. This is for local pickup only in the Tampa area. You may arrange for shipping and have them pick it up, or I can possibly drop it off at a nearby shipper if you set up and pre-pay, make your own arrangements. This will most likely require a pallet.Thanks for looking!",
        "ItemID":"223348187115",
        "EndTime":"2019-02-07T02:03:19.000Z",
        "StartTime":"2019-01-28T02:03:19.000Z",
        "ViewItemURLForNaturalSearch":"https://www.ebay.com/itm/ALTEC-Early-Model-606-Corner-Cabinet-602A-15-Duplex-Speaker-N3000A-/223348187115",
        "ListingType":"Chinese",
        "Location":"Palm Harbor, Florida",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"https://thumbs4.ebaystatic.com/pict/2233481871158080_1.jpg",
        "PictureURL":[
            "https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/QA8AAOSw5oxb5I4T/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/SyAAAOSwMg5b5I4T/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/8ewAAOSwIKNb5I4T/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/NjQwWDQ4MA==/z/tNEAAOSwC8pb5JML/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/NjQwWDQ4MA==/z/gCkAAOSwAPtb5JML/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/hrYAAOSwhexb5JMK/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/lLMAAOSwZ3pb5JMK/$_32.JPG?set_id=880000500F"],
        "PostalCode":"34684",
        "PrimaryCategoryID":"50597",
        "PrimaryCategoryName":"Consumer Electronics:Vintage Electronics:Vintage Audio & Video:Vintage Speakers",
        "Quantity":1,
        "Seller":{"UserID":"anthoquanc","FeedbackRatingStar":"Turquoise","FeedbackScore":145,"PositiveFeedbackPercent":100.0},
        "BidCount":0,
        "ConvertedCurrentPrice":{"Value":1200.0,"CurrencyID":"USD"},"CurrentPrice":{"Value":1200.0,"CurrencyID":"USD"},
        "ListingStatus":"Completed",
        "QuantitySold":0,
        "ShipToLocations":["None"],
        "Site":"US",
        "TimeLeft":"PT0S",
        "Title":"ALTEC Early Model 606 Corner Cabinet 602A 15\\" Duplex Speaker  N3000A ",
        "HitCount":118,
        "PrimaryCategoryIDPath":"293:183077:175740:50597",
        "Country":"US",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted"},
        "MinimumToBid":{"Value":1200.0,"CurrencyID":"USD"},"AutoPay":false,
        "PaymentAllowedSite":[],"IntegratedMerchantCreditCardEnabled":false,"ExcludeShipToLocation":["PO Box"],"GlobalShipping":false,"QuantitySoldByPickupInStore":0,"NewBestOffer":false}}'''


# among sResponseItems2Test
s173696834267 = '''{
    "Timestamp":"2019-03-24T02:21:45.250Z",
    "Ack":"Success",
    "Build":"E1089_CORE_APILW_18879361_R1","Version":"1089",
    "Item":{"BestOfferEnabled":false,
        "Description":"1 Vintage NOS Tested Westinghouse 12AU7 Vacuum tube! Please see the detailed pictures below Please see shipping calculator for shipping costs, Item is located in Vancovuer BC and can be shipped with the USPS out of Washington state or Canada Post for Canadian buyers. items over $120 will not be shipped without tracking which can be pricey to some overseas locations. Please see below for details on shipping. 1 Vintage NOS Westinghouse 12AU7 vacuum tube. Tube is made in Canada and features grey plates and an O getter. The tube is new and unused. Tubes have been tested on a Daniel Nelson Calibrated Hickok TV7 tube tester and test as follows:Tube1 : 112/110 Minimun good value on a TV7 tester for a 12au7 tube is 56. The tubes test within the NOS range!Tubes are guaranteed to be in good working order upon delivery. If a tube ends up bad within 1 week of delivery just ship it back for a full refund on the bad tube minus shipping costs. See pictures for details. If you have any questions please email. I will ship worldwide.Buyer to pay all shipping costs including brokerage and taxes if any. Item is located in Canada but will be shipped with the USPS for USA buyers or Canada Post for Canadian buyers. For overseas buyers : Please email for options as sometimes Canada post is cheaper for overseas shipping with Surface post or airmail. Please wait for my invoice before paying to avoid any hassles. I do combine shipping to save you costs! See my other auctions for more vintage audio gear! Local pickup in Vancouver BC is also available. GOOD LUCK!!!!!!!",
        "ItemID":"173696834267",
        "EndTime":"2018-12-25T03:10:30.000Z",
        "StartTime":"2018-12-18T03:10:30.000Z",
        "ViewItemURLForNaturalSearch":"https://www.ebay.com/itm/1-NOS-Westinghouse-Canada-12au7A-12au7-Vacuum-Tube-TV7-Tested-Guaranteed-NR-/173696834267",
        "ListingType":"Chinese",
        "Location":"Point Roberts, Washington",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"https://thumbs4.ebaystatic.com/pict/1736968342678080_1.jpg",
        "PictureURL":[
            "https://i.ebayimg.com/00/s/NjQwWDQ4MA==/z/nTsAAOSwxH1UJIw1/$_1.JPG?set_id=880000500F"],
        "PostalCode":"98281",
        "PrimaryCategoryID":"64627",
        "PrimaryCategoryName":"Consumer Electronics:Vintage Electronics:Vintage Audio & Video:Vintage Parts & Accessories:Vintage Tubes & Tube Sockets",
        "Quantity":1,
        "Seller":{"UserID":"stevestonaudiosales","FeedbackRatingStar":"Red","FeedbackScore":2309,"PositiveFeedbackPercent":100.0,"TopRatedSeller":true},
        "BidCount":0,
        "ConvertedCurrentPrice":{"Value":9.99,"CurrencyID":"USD"},"CurrentPrice":{"Value":9.99,"CurrencyID":"USD"},
        "ListingStatus":"Completed",
        "QuantitySold":0,
        "ShipToLocations":["Worldwide"],
        "Site":"US",
        "TimeLeft":"PT0S",
        "Title":"1 NOS Westinghouse Canada 12au7A 12au7 Vacuum Tube TV7 Tested Guaranteed! NR! ",
        "HitCount":5,
        "PrimaryCategoryIDPath":"293:183077:175740:175741:64627","Storefront":{"StoreURL":"https://stores.ebay.com/id=22208173","StoreName":"stevestonaudiosales"},
        "Country":"US",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted"},
        "MinimumToBid":{"Value":9.99,"CurrencyID":"USD"},"AutoPay":false,
        "PaymentAllowedSite":[],"IntegratedMerchantCreditCardEnabled":false,
        "HandlingTime":3,"GlobalShipping":false,
        "ConditionDescription":"Fully Tested Guaranteed Vacuum tubes.","QuantitySoldByPickupInStore":0,"NewBestOffer":false}}'''


# among sResponseItems2Test
s372536713027 = '''{
    "Timestamp":"2019-03-24T02:23:07.637Z",
    "Ack":"Success",
    "Build":"E1089_CORE_APILW_18879361_R1","Version":"1089",
    "Item":{"BestOfferEnabled":false,"BuyItNowPrice":{"Value":19.0,"CurrencyID":"USD"},
        "Description":"NOS 6SN7GTB in original box. Test good. Works or money back in 2 weeks.",
        "ItemID":"372536713027","BuyItNowAvailable":true,"ConvertedBuyItNowPrice":{"Value":19.0,"CurrencyID":"USD"},
        "EndTime":"2018-12-22T18:57:57.000Z",
        "StartTime":"2018-12-15T18:57:57.000Z",
        "ViewItemURLForNaturalSearch":"https://www.ebay.com/itm/VINTAGE-RCA-6SN7GTB-ELECTRON-TUBE-NOS-/372536713027",
        "ListingType":"Chinese",
        "Location":"Lincoln University, Pennsylvania",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"https://thumbs4.ebaystatic.com/pict/3725367130278080_1.jpg",
        "PictureURL":[
            "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/3ZcAAOSwaSVcFU49/$_57.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/3vkAAOSwLNxcFU4~/$_57.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/2GoAAOSwIddcFU5D/$_57.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/ZiUAAOSw-GNcFU5I/$_57.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/hR4AAOSw76lcFU5N/$_57.JPG?set_id=8800005007"],
        "PostalCode":"19352",
        "PrimaryCategoryID":"64627",
        "PrimaryCategoryName":"Consumer Electronics:Vintage Electronics:Vintage Audio & Video:Vintage Parts & Accessories:Vintage Tubes & Tube Sockets",
        "Quantity":1,
        "Seller":{"UserID":"mssuzicue","FeedbackRatingStar":"Red","FeedbackScore":3010,"PositiveFeedbackPercent":100.0},
        "BidCount":0,
        "ConvertedCurrentPrice":{"Value":14.5,"CurrencyID":"USD"},"CurrentPrice":{"Value":14.5,"CurrencyID":"USD"},
        "ListingStatus":"Completed",
        "QuantitySold":0,
        "ShipToLocations":["US"],
        "Site":"US",
        "TimeLeft":"PT0S",
        "Title":"VINTAGE RCA 6SN7GTB ELECTRON TUBE NOS",
        "HitCount":20,
        "PrimaryCategoryIDPath":"293:183077:175740:175741:64627",
        "Country":"US",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted","InternationalReturnsAccepted":"ReturnsNotAccepted"},
        "MinimumToBid":{"Value":14.5,"CurrencyID":"USD"},"AutoPay":false,
        "PaymentAllowedSite":[],"IntegratedMerchantCreditCardEnabled":false,
        "HandlingTime":0,"GlobalShipping":false,"QuantitySoldByPickupInStore":0,"NewBestOffer":false}}'''


# among sResponseItems2Test
s173696832184 = '''{
    "Timestamp":"2019-03-24T02:24:39.595Z",
    "Ack":"Success",
    "Build":"E1089_CORE_APILW_18879361_R1","Version":"1089",
    "Item":{"BestOfferEnabled":false,
        "Description":"2 Vintage Tested Philips Holland made but GE branded 6DJ8 / ECC88 / 6922 Vacuum tubes! Please see shipping calculator for shipping costs, Item is located in Vancovuer BC and can be shipped with the USPS out of Washington state or Canada Post for Canadian buyers. items over $120 will not be shipped without tracking which can be pricey to some overseas locations. Please see below for details on shipping. Up for auction are 2 vintage Philips Holland made but GE Branded 6DJ8 vacuum tubes. Tubes have been tested on a Calibrated Hickok TV7 tube tester and test as follows:Tube1 : 102/88 Tube2 : 86/86 Minimum good value on a TV7 tester for a 6DJ8 tube is 62. The tubes tests within the NOS range!Tubes are guaranteed to be in good working order upon delivery. If a tube ends up bad within 1 week of delivery just ship it back for a full refund on the bad tube minus shipping costs. See pictures for details. If you have any questions please email. I will ship worldwide.Buyer to pay all shipping costs including brokerage and taxes if any. Item is located in Canada but will be shipped with the USPS for USA buyers or Canada Post for Canadian buyers. For overseas buyers : Please email for options as sometimes Canada post is cheaper for overseas shipping with Surface post. Please wait for my invoice before paying to avoid any hassles. I do combine shipping to save you costs! See my other auctions for more vintage audio gear! Local pickup in Vancouver BC is also available. GOOD LUCK!!!!!!!",
        "ItemID":"173696832184",
        "EndTime":"2018-12-25T03:07:28.000Z",
        "StartTime":"2018-12-18T03:07:28.000Z",
        "ViewItemURLForNaturalSearch":"https://www.ebay.com/itm/2-Vintage-Philips-Holland-GE-6DJ8-6922-E88CC-Vacuum-Tubes-Tested-Guaranteed-/173696832184",
        "ListingType":"Chinese",
        "Location":"Point Roberts, Washington",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"https://thumbs1.ebaystatic.com/pict/1736968321848080_1.jpg",
        "PictureURL":[
            "https://i.ebayimg.com/00/s/OTYwWDEyODA=/z/4cgAAOSwXetZWIrq/$_1.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/OTYwWDEyODA=/z/oBkAAOSw8GtZWIrr/$_1.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTI4MFg5NjA=/z/JVcAAOSwbtVZWIrt/$_1.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTI4MFg5NjA=/z/X1EAAOSwyltZWIrv/$_1.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTI4MFg5NjA=/z/nSwAAOSw-29ZWIrx/$_1.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTI4MFg5NjA=/z/E30AAOSwiQ9ZWIrz/$_1.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTI4MFg5NjA=/z/NgsAAOSwz71ZWIr1/$_1.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTI4MFg5NjA=/z/6eMAAOSwTf9ZWIr3/$_1.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTI4MFg5NjA=/z/eiMAAOSwrfVZWIr5/$_1.JPG?set_id=8800005007"],
        "PostalCode":"98281",
        "PrimaryCategoryID":"64627",
        "PrimaryCategoryName":"Consumer Electronics:Vintage Electronics:Vintage Audio & Video:Vintage Parts & Accessories:Vintage Tubes & Tube Sockets",
        "Quantity":1,
        "Seller":{"UserID":"stevestonaudiosales","FeedbackRatingStar":"Red","FeedbackScore":2309,"PositiveFeedbackPercent":100.0,"TopRatedSeller":true},
        "BidCount":0,
        "ConvertedCurrentPrice":{"Value":58.88,"CurrencyID":"USD"},"CurrentPrice":{"Value":58.88,"CurrencyID":"USD"},
        "ListingStatus":"Completed",
        "QuantitySold":0,
        "ShipToLocations":["Worldwide"],
        "Site":"US",
        "TimeLeft":"PT0S",
        "Title":"2 Vintage Philips Holland GE  6DJ8 6922 E88CC Vacuum Tubes Tested Guaranteed!",
        "HitCount":21,
        "PrimaryCategoryIDPath":"293:183077:175740:175741:64627","Storefront":{"StoreURL":"https://stores.ebay.com/id=22208173","StoreName":"stevestonaudiosales"},
        "Country":"US",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted"},
        "MinimumToBid":{"Value":58.88,"CurrencyID":"USD"},"AutoPay":false,
        "PaymentAllowedSite":[],"IntegratedMerchantCreditCardEnabled":false,
        "HandlingTime":3,"GlobalShipping":false,
        "ConditionDescription":"Fully Tested Guaranteed Vacuum tubes.","QuantitySoldByPickupInStore":0,"NewBestOffer":false}}'''


# among sResponseItems2Test
s303000971114 = '''{
    "Timestamp":"2019-03-24T02:26:25.111Z",
    "Ack":"Success",
    "Build":"E1089_CORE_APILW_18879361_R1","Version":"1089",
    "Item":{"BestOfferEnabled":false,
        "Description":"3 vintage Matsushita Golden Series, earliest version, EL34/6CA7 power tubes, early version flat top series with dual round getters, incomparable vintage quality, design, craftsmanship, attention to detail, sound quality and performance. They sound superb and are highest quality copies of vintage European tubes. They are made in Japan. They all test very very strong and very close together on my B&K mutual conductance tube tester. They test 910/905/908, where 640 is minimum good. The also have a Positive Life test which tests the tube for longevity. They are all identical and were made in the late 1950s. The shipping cost includes safe packing, insurance, prompt shipping and tracking number. Buy with confidence, see my feedback. Good listening, SonnY :)",
        "ItemID":"303000971114",
        "EndTime":"2018-12-25T03:36:20.000Z",
        "StartTime":"2018-12-18T03:36:20.000Z",
        "ViewItemURLForNaturalSearch":"https://www.ebay.com/itm/3-Vintage-Matsushita-EL34-6CA7-Golden-Series-Tubes-1950s-Dual-Getters-EX-sound-/303000971114",
        "ListingType":"Chinese",
        "Location":"Fort Walton Beach, Florida",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"https://thumbs3.ebaystatic.com/pict/3030009711148080_1.jpg",
        "PictureURL":[
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/6lsAAOSwnhJbqRjl/$_57.JPG?set_id=8800005007",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/KbsAAOSwy2pbqRjr/$_57.JPG?set_id=8800005007"],
        "PostalCode":"32547",
        "PrimaryCategoryID":"64627",
        "PrimaryCategoryName":"Consumer Electronics:Vintage Electronics:Vintage Audio & Video:Vintage Parts & Accessories:Vintage Tubes & Tube Sockets",
        "Quantity":1,
        "Seller":{"UserID":"sonnysound8uxj","FeedbackRatingStar":"Green","FeedbackScore":6553,"PositiveFeedbackPercent":100.0,"TopRatedSeller":true},
        "BidCount":0,
        "ConvertedCurrentPrice":{"Value":168.0,"CurrencyID":"USD"},"CurrentPrice":{"Value":168.0,"CurrencyID":"USD"},
        "ListingStatus":"Completed",
        "QuantitySold":0,
        "ShipToLocations":["Worldwide"],
        "Site":"US",
        "TimeLeft":"PT0S",
        "Title":"3 Vintage Matsushita EL34 6CA7 Golden Series Tubes,1950s,Dual Getters,EX sound",
        "HitCount":14,
        "PrimaryCategoryIDPath":"293:183077:175740:175741:64627","Storefront":{"StoreURL":"https://stores.ebay.com/id=1200879","StoreName":"Goldie Store"},
        "Country":"US",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted","InternationalReturnsAccepted":"ReturnsNotAccepted"},
        "MinimumToBid":{"Value":168.0,"CurrencyID":"USD"},"AutoPay":false,
        "PaymentAllowedSite":[],"IntegratedMerchantCreditCardEnabled":false,
        "HandlingTime":1,"GlobalShipping":false,
        "ConditionDescription":"They all 3 test very strong on my B&K Mutual Conductance Tube tester, early version flat top 1950s Golden Series, Ex sound, JAPAN","QuantitySoldByPickupInStore":0,"NewBestOffer":false}}'''


# among sResponseItems2Test
s323589685342 = '''{
    "Timestamp":"2019-03-24T02:32:28.518Z",
    "Ack":"Failure",
    "Errors":[{"ShortMessage":"Invalid item ID.",
    "LongMessage":"Invalid or non-existent item ID.",
    "ErrorCode":"10.12",
    "SeverityCode":"Error",
    "ErrorClassification":"RequestError"}],
    "Build":"E1089_CORE_APILW_18879361_R1",
    "Version":"1089"}'''

# not among sResponseItems2Test
s142766343340 = '''{
    "Timestamp":"2018-04-28T01:09:38.251Z",
    "Ack":"Success",
    "Build":"E1057_CORE_APILW_18679933_R1","Version":"1057",
    "Item":{
        "BestOfferEnabled":true,
        "Description":"1946 Bendix Catalin Radio Model 506MC. The radio is in excellent condition. It has no cracks and has all original parts. The radio is in working condition. The case has a rich green marble finish. This is a very nice Catalin radio that shows extremely well, Packaged with care and ships quickly. Thank you for your interest.",
        "ItemID":"142766343340",
        "EndTime":"2018-05-22T00:09:44.000Z",
        "StartTime":"2018-04-22T00:09:44.000Z",
        "ViewItemURLForNaturalSearch":"http://www.ebay.com/itm/1946-Bendix-Catalin-Radio-Model-526MC-/142766343340",
        "ListingType":"FixedPriceItem",
        "Location":"West Linn, Oregon",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"http://thumbs1.ebaystatic.com/pict/1427663433408080_1.jpg",
        "PictureURL":[
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/FQwAAOSwaC9afy39/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTEzNFgxNjAw/z/9wUAAOSwSwVafy3-/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/UkYAAOSwE7Jafy4C/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/zaoAAOSw9V1afzCQ/$_12.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/5x8AAOSwxM5afy3~/$_0.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMTM0/z/plEAAOSwY7tafy6R/$_12.JPG?set_id=880000500F"],
        "PostalCode":"97068",
        "PrimaryCategoryID":"38034",
        "PrimaryCategoryName":"Collectibles:Radio, Phonograph, TV, Phone:Radios:Tube Radios:1930-49",
        "Quantity":1,
        "Seller":{"UserID":"nordic1000",
        "FeedbackRatingStar":"Blue",
        "FeedbackScore":65,"PositiveFeedbackPercent":100.0},
        "BidCount":0,
        "ConvertedCurrentPrice":{"Value":945.0,"CurrencyID":"USD"},
        "CurrentPrice":{"Value":945.0,"CurrencyID":"USD"},
        "ListingStatus":"Active",
        "QuantitySold":0,
        "ShipToLocations":["US"],
        "Site":"US",
        "TimeLeft":"P23DT23H6S",
        "Title":"1946 Bendix Catalin Radio - Model 526MC",
        "HitCount":35,
        "PrimaryCategoryIDPath":"1:29832:931:38032:38034",
        "Country":"US",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted"},
        "AutoPay":false,
        "PaymentAllowedSite":[],
        "IntegratedMerchantCreditCardEnabled":false,
        "HandlingTime":2,
        "ConditionID":3000,
        "ConditionDisplayName":"Used",
        "GlobalShipping":false,"QuantitySoldByPickupInStore":0,"NewBestOffer":false}}'''


# not among sResponseItems2Test
s232742493872 = '''{
    "Timestamp":"2018-04-25T21:34:30.002Z",
    "Ack":"Success",
    "Build":"E1057_CORE_APILW_18679933_R1","Version":"1057",
    "Item":{
        "BestOfferEnabled":false,
        "BuyItNowPrice":{"Value":150.0,"CurrencyID":"USD"},
        "Description":"SUPERB MATCHED PAIR OF 1940'S JAN CHS 6SL7 GT DUAL TRIODE AUDIO AMPLIFIER VACUUM TUBES BY SYLVANIA !! GREAT BLACK TUBULAR PLATE MATCHED SET !! 2 TOP QUALITY TUBES MADE TO MILITARY SPECIFICATIONS ! THEY HAVE NO SHORTS OR GAS AND TEST NEW OLD STOCK , VERY STRONG, ON A TV-7/U MILITARY TUBE TESTER WITH READINGS OF 56 / 57 AND 57 / 57 WITH 32 SPECIFIED FOR A GOOD TUBE !! THE PRODUCTION/MANUFACTURING CODE IS 4B ON BOTH TUBES ! THE TUBES ARE IN EXCELLENT PHYSICAL CONDITION TOO WITH NICE SILVERING AND CLEAR PRINTING !! ( FOR CONDITION SEE THE PICTURES. ) A GREAT MATCHED PAIR OF SUPERB MILITARY QUALITY TUBES !! THERE IS NO RESERVE SO BID CONFIDENT THAT THESE GREAT 6SL7 GT TUBES WILL SOON BE YOURS !! OR USE BUY IT NOW AND BE SURE !! AND SHIPPING IS FREE ! (310u3s) \\"> Powered by eBay Turbo Lister The free listing tool. List your items fast and easy and manage your active items.",
        "ItemID":"232742493872",
        "BuyItNowAvailable":true,
        "ConvertedBuyItNowPrice":{"Value":150.0,"CurrencyID":"USD"},
        "EndTime":"2018-05-02T03:37:05.000Z",
        "StartTime":"2018-04-22T03:37:05.000Z",
        "ViewItemURLForNaturalSearch":"http://www.ebay.com/itm/SUPERB-1940s-JAN-6SL7GT-VT-229-AMPLIFER-TUBES-TESTED-NOS-/232742493872",
        "ListingType":"Chinese",
        "Location":"Belgrade",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"http://thumbs1.ebaystatic.com/pict/2327424938728080_1.jpg",
        "PictureURL":["http://i.ebayimg.com/00/s/NDgwWDY0MA==/z/-qUAAOSwIM9a3ANg/$_1.JPG?set_id=8800005007"],
        "PostalCode":"98310",
        "PrimaryCategoryID":"64627",
        "PrimaryCategoryName":"Consumer Electronics:Vintage Electronics:Vintage Audio & Video:Vintage Parts & Accessories:Vintage Tubes & Tube Sockets",
        "Quantity":1,
        "Seller":{"UserID":"pardneer",
        "FeedbackRatingStar":"Red","FeedbackScore":1672,"PositiveFeedbackPercent":100.0},
        "BidCount":0,
        "ConvertedCurrentPrice":{"Value":100.0,"CurrencyID":"USD"},
        "CurrentPrice":{"Value":100.0,"CurrencyID":"USD"},
        "ListingStatus":"Active",
        "QuantitySold":0,
        "ShipToLocations":["Worldwide"],
        "Site":"US",
        "TimeLeft":"P6DT6H2M36S",
        "Title":"SUPERB 1940's JAN 6SL7GT VT-229 AMPLIFER TUBES ! TESTED NOS",
        "HitCount":6,
        "PrimaryCategoryIDPath":"293:183077:175740:175741:64627",
        "Country":"CustomCode",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted"},
        "MinimumToBid":{"Value":100.0,"CurrencyID":"USD"},
        "AutoPay":false,
        "PaymentAllowedSite":[],
        "IntegratedMerchantCreditCardEnabled":false,
        "HandlingTime":5,
        "GlobalShipping":false,
        "QuantitySoldByPickupInStore":0,
        "SKU":"2018-04  310u3s",
        "NewBestOffer":false}}'''



# not among sResponseItems2Test
s232709513135 = '''{
    "Timestamp":"2018-04-25T21:05:51.846Z",
    "Ack":"Success",
    "Build":"E1057_CORE_APILW_18679933_R1","Version":"1057",
    "Item":{
        "BestOfferEnabled":false,
        "Description":"Update I powered up the amp on my Variac and brought it up to full power very slowly over the period of about 4 hours. I added a picture of the amp showing it powered up and another picture showing the tube glowing. So now everyone knows that the amp powers up and I feel a little better too knowing that it still works. Good luck and I have now added the best offer feature for those that would like to make me a reasonable offer can do so. Offered here is a vintage FISHER 400C pre-amplifier. This amp has almost a perfect face plate and the chassis looks good as well just dusty and dirty. I took a rag to a couple of areas and washed off some of the dirt as it has been sitting in the garage for well over 12 years collecting dust and dirt. Many years ago the amp had the selenium rectifier replaced with solid state diodes and some capacitors were also changed at that time as well. All of the controls move freely and very smooth! The tubes are not the original Telefunken tubes. I saw one Telefunken, a bugle boy and the rest were all vintage American tubes, no foreign junk tubes. The amp worked fine before it was put away. Look at my feedback I don\u2019t sell junk. This amp will be packaged very well and will be double boxed to ensure it arrives safely as shown. Please ask any questions you may have prior to purchasing the amp. Thanks for looking. Overseas shipping on this item by Priority Mail only, Registered with delivery notification, No exceptions please don't ask if I can ship it economy!!",
        "ItemID":"232709513135",
        "EndTime":"2018-04-01T01:35:17.000Z",
        "StartTime":"2018-03-25T01:35:17.000Z",
        "ViewItemURLForNaturalSearch":"http://www.ebay.com/itm/Fisher-400C-Stereophonic-Tube-Pre-Amplifier-Rare-and-Excellent-Condition-/232709513135",
        "ListingType":"Chinese",
        "Location":"Victorville, California",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"http://thumbs4.ebaystatic.com/pict/2327095131358080_2.jpg",
        "PictureURL":[
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/wZIAAOSwaadauaBY/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/F5UAAOSw08pauaCh/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/D0MAAOSwQXBatvGF/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/UsYAAOSwvshatvIa/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/Q7IAAOSwzwxatvIa/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/ktYAAOSw1utatvIb/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/TI8AAOSwyO1atvIb/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/7zEAAOSwACRatvLN/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/KNYAAOSwlJlatvJy/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/mqcAAOSw0wtauDTn/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/424AAOSw7VhauDUk/$_32.JPG?set_id=880000500F",
            "https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/nYwAAOSwGbhauDUo/$_32.JPG?set_id=880000500F"],
        "PostalCode":"92395",
        "PrimaryCategoryID":"67807",
        "PrimaryCategoryName":"Consumer Electronics:Vintage Electronics:Vintage Audio & Video:Vintage Preamps & Tube Preamps",
        "Quantity":1,
        "Seller":{"UserID":"besttubes4u","FeedbackRatingStar":"Red","FeedbackScore":1272,"PositiveFeedbackPercent":100.0},
        "BidCount":15,
        "ConvertedCurrentPrice":{"Value":866.0,"CurrencyID":"USD"},
        "CurrentPrice":{"Value":866.0,"CurrencyID":"USD"},
        "HighBidder":{"UserID":"z***k","FeedbackPrivate":false,"FeedbackRatingStar":"Red","FeedbackScore":2394},
        "ListingStatus":"Completed",
        "QuantitySold":1,
        "ShipToLocations":["Worldwide"],
        "Site":"US",
        "TimeLeft":"PT0S",
        "Title":"Fisher 400C 'Stereophonic' Tube Pre-Amplifier Rare and In Excellent Condition",
        "HitCount":768,
        "PrimaryCategoryIDPath":"293:183077:175740:67807",
        "Country":"US",
        "ReturnPolicy":{"ReturnsAccepted":"ReturnsNotAccepted"},
        "MinimumToBid":{"Value":876.0,"CurrencyID":"USD"},
        "AutoPay":false,
        "PaymentAllowedSite":[],
        "IntegratedMerchantCreditCardEnabled":false,
        "HandlingTime":3,
        "GlobalShipping":false,
        "QuantitySoldByPickupInStore":0,
        "NewBestOffer":false}}'''

# this is dSearchResult item
s282330751118 = '''{
    "Timestamp":"2018-06-17T02:46:33.737Z",
    "Ack":"Success",
    "Build":"E1065_CORE_APILW_18725136_R1","Version":"1065",
    "Item":{
        "BestOfferEnabled":true,
        "Description":"Digital Capacitance Tester Capacitor Meter Auto Range Multimeter Checker 470mF Features: -Brand：Excelvan -Larger measuring range,read up to 470mF/ 470000uF -With auto running averaging function, can read pF more stable and accuracy -Easy to use and fast response time on measuring from 0.01pF to 470000uF Note: 1.*Accuracy maybe affected by the test lead&rsquo;s length and distance of test leads. Especially testing pF small capacitance, shortest test lead is recommended, and be careful the surrounding EMI or RF noise may affect the pF reading. 2.PLEASE DISCHARGE THE CAPACITOR BEFORE TESTING, you can use a screwdriver to short circuit, or series with a resistor around 10 ohm and short for 5 to 10s. There is 1 fast zener diode inside the meter to prevent high voltage, but it is important to discharge the capacitor firstly, as it is a large surge current and voltage and may damage the meter. Package Content 1 X Digital Capacitance Meter 1 X pair test probe Operating Introduction: - POWER ON Press and hold the ON/ OFF circle orange button for 1 to 2 second to power on. Press and release the ON/ OFF button to shut down meter. - AUTO/ MANUAL mode: Auto Range: Press and release the RANGE button and at the first line of LCD will show \\"AUTO:\\" At auto mode meter will automatically select the best range to detect. Manual Range: Scroll the manual range from 47nF, 47uF and 470mF range by press and release the RANGE button In LCD will show MANUAL at first LCD line and show at second line: 0-47NF, 47NF TO 47UF and 47UF TO 470MF. 1 Key Zero: OPEN circuit the test leads terminal. Press and release the &ldquo;ZERO\\" button, LCD shows &ldquo;ZERO\\" and wait the zero disappear. If you are using the meter array socket, you need to OPEN circuit to set zero too. Socket: You can use the 8 pin socket to measure the capacitor Running Average: It will automatically start running average if the capacitance reading become stable and user can get more accuracy reading. During running average it will show &ldquo;AVG&rdquo; at right bottom LCD or it will show raw data icon &ldquo;RAW&rdquo; As a result, if you want to get higher accuracy reading, you can take the reading during AVG display. This function will automatically on, once the raw data is noise. Backlight: LCD backlight will on during power on Auto Sleep: Around 8 to 10 hours for not testing, it will shut down automatically to save power. OVERFLOW or OL: Display overflow when the value is out of range, you can check that you are zero correctly. Specification: Range Accuracy (After Zero, tested with 1nF, 1uF, 1000uF) Refresh Time (Manual Mode) *Auto mode take 0 to 2s more time depend on value Larger capacitance take more measuring time 0.01pF to 47.000nF 1%+2Digit ~0.2s to 1s 47.00nF to 47.000uF 1%+1Digit ~0.2s to 2s 47.00uF to 470.00mF 1 to 3%+1Digit (Larger capacitance will have larger error) ~0.2s to 30s Accuracy Up to 1% (detail on above table) High Resolution 5 digit Measuring voltage <0.8V Clamping voltage ~1.25V (open voltage) Battery 2X AA 1.5V battery(Not Included) Operating current 0.02A Payment Method ★We accept PayPal only. ★NOTE: Payment should be sent within 4 (FOUR) days of auction closing. Or unpaid dispute will be filed for closing auction. Please contact us if you have any questions of payment procedures. Shipping Policy ★How much is shipping and handling (S&H)? The shipping and handling costs will be clearly marked on the auction item page. ★Please make sure the Ship-To address you type during checkout is correct. We are not responsible for any wrong or undeliverable addresses. ★Local pick up is not available. ★Items are generally shipped out the next business day after your payment has been cleared (Sat. & Sun. excluded.). ★An e-mail will be sent to your eBay e-mail address upon item is shipped out. If you do not receive this e-mail in 48 Business Hours, please contact us to check the status of your transaction. . ★International Buyers - Please Note: Import duties, taxes, and charges are not included in the item price or shipping cost. These charges are the buyer's responsibility. Please check with your country's customs office to determine what these additional costs will be prior to bidding or buying. Customs fees are normally charged by the shipping company or collected when you pick the item up. These fees are not additional shipping charges. Return & Warranty ★Our items come with one-year warranty. ★Our warranty does not extended to any products that are physically damaged or that are not under normal operating conditions as a result of misuse or improper installation on the buyer/user's part. ★This product comes with 30-Day Money Back Guarantee. ★We stand behind every product we sell. If you're not pleased with your purchase, we'll be happy to make an exchange or refund. ★For all returned products, please contact us for the returning address. Reply ★ALL replies will be sent to your email, if you don't get response within 1-2 business days, pls check your My Messages in case your email provider has an overly-aggressive spam filterblocking eBay's emails. Please email us AGAIN. ★Email is the priority of our customer service. Feedback ★You will receive our positive feedback as soon as you pay for your item.  ★Your better comments will be an encouragement for us to offer the better quality and the better service in future. ★If you are not satisfied with them, please contact us first via Ask a Question or via Contact Seller. Your messages will be answered within 1-2 business day. We shall try our best to solve your problem to your satisfaction.",
        "ItemID":"282330751118",
        "EndTime":"2018-06-13T00:34:26.000Z",
        "StartTime":"2017-01-19T00:34:26.000Z",
        "ViewItemURLForNaturalSearch":
            "http://www.ebay.com/itm/Digital-Capacitance-Tester-Capacitor-Meter-Auto-Range-Multimeter-Checker-470mF-/282330751118",
        "ListingType":"FixedPriceItem",
        "Location":"Staten Island, New York",
        "PaymentMethods":["PayPal"],
        "GalleryURL":"http://thumbs3.ebaystatic.com/pict/2823307511188080_1.jpg",
        "PictureURL":[
            "http://i.ebayimg.com/00/s/MTAyNFgxMDI0/z/TvsAAOSwnHZYgAlk/$_12.JPG?set_id=880000500F",
            "http://i.ebayimg.com/00/s/MTAyNFgxMDI0/z/DTEAAOSwLEtYgAlm/$_12.JPG?set_id=880000500F",
            "http://i.ebayimg.com/00/s/MTAyNFgxMDI0/z/EZYAAOSwt5hYgAlo/$_12.JPG?set_id=880000500F",
            "http://i.ebayimg.com/00/s/MTAyNFgxMDI0/z/EbEAAOSwt5hYgAlq/$_12.JPG?set_id=880000500F",
            "http://i.ebayimg.com/00/s/MTAyNFgxMDI0/z/34IAAOSw2xRYgAlt/$_12.JPG?set_id=880000500F",
            "http://i.ebayimg.com/00/s/MTAyNFgxMDI0/z/eJ0AAOSw-0xYgAlv/$_12.JPG?set_id=880000500F",
            "http://i.ebayimg.com/00/s/MTAyNFgxMDI0/z/2ZUAAOSw9GhYgAlx/$_12.JPG?set_id=880000500F"],
        "PostalCode":"10303",
        "PrimaryCategoryID":"73160",
        "PrimaryCategoryName":"Business & Industrial:Electrical & Test Equipment:Test, Measurement & Inspection:Test Meters & Detectors:Capacitance & ESR Meters",
        "Quantity":23,
        "Seller":{
            "UserID":"blissmall",
            "FeedbackRatingStar":"YellowShooting",
            "FeedbackScore":10052,
            "PositiveFeedbackPercent":99.1,
            "TopRatedSeller":true},
        "BidCount":0,
        "ConvertedCurrentPrice":{"Value":25.99,"CurrencyID":"USD"},
        "CurrentPrice":{"Value":25.99,"CurrencyID":"USD"},
        "ListingStatus":"Completed",
        "QuantitySold":23,
        "ShipToLocations":["US"],
        "Site":"US",
        "TimeLeft":"PT0S",
        "Title":"Digital Capacitance Tester Capacitor Meter Auto Range Multimeter Checker 470mF",
        "HitCount":1662,
        "PrimaryCategoryIDPath":"12576:92074:181939:181968:73160",
        "Storefront":{
            "StoreURL":"http://stores.ebay.com/id=1552145652",
            "StoreName":"Blissmall.Inc"},
        "Country":"US",
        "ReturnPolicy":{
            "Refund":"Money Back",
            "ReturnsWithin":"30 Days",
            "ReturnsAccepted":"Returns Accepted",
            "Description":"Returns Accepted, Buyer, 30 Days, Money Back",
            "ShippingCostPaidBy":"Buyer"},
        "AutoPay":false,
        "PaymentAllowedSite":[],
        "IntegratedMerchantCreditCardEnabled":false,
        "HandlingTime":1,
        "ConditionID":1000,
        "ConditionDisplayName":"New",
        "ExcludeShipToLocation":[
            "Alaska/Hawaii","APO/FPO","US Protectorates","Africa","Asia",
            "Central America and Caribbean","Europe","Middle East",
            "North America","Oceania","Southeast Asia","South America"],
        "TopRatedListing":true,
        "GlobalShipping":false,
        "QuantitySoldByPickupInStore":0,
        "SKU":"138764001",
        "NewBestOffer":false}}'''


sPicList = '''[
    "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/UZQAAOSw4dtalxRS/$_32.JPG?set_id=880000500F",
    "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/RNkAAOSwQ-JalxRY/$_32.JPG?set_id=880000500F",
    "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/HuYAAOSwETlalxRe/$_32.JPG?set_id=880000500F",
    "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/x3sAAOSwZEValxRp/$_32.JPG?set_id=880000500F",
    "https://i.ebayimg.com/00/s/MTYwMFgxMDY2/z/07oAAOSwoDValxRt/$_32.JPG?set_id=880000500F",
    "https://i.ebayimg.com/00/s/MTYwMFgxMDY2/z/uFYAAOSweutalxRw/$_32.JPG?set_id=880000500F",
    "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/pM4AAOSwAwpalxR3/$_32.JPG?set_id=880000500F",
    "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/ZiUAAOSwfNxalxR7/$_32.JPG?set_id=880000500F",
    "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/cl4AAOSw0kValxSD/$_32.JPG?set_id=880000500F",
    "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/sHkAAOSwRYFalxS2/$_32.JPG?set_id=880000500F"]'''

sExpectList = '''https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/UZQAAOSw4dtalxRS/$_32.JPG?set_id=880000500F
https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/RNkAAOSwQ-JalxRY/$_32.JPG?set_id=880000500F
https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/HuYAAOSwETlalxRe/$_32.JPG?set_id=880000500F
https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/x3sAAOSwZEValxRp/$_32.JPG?set_id=880000500F
https://i.ebayimg.com/00/s/MTYwMFgxMDY2/z/07oAAOSwoDValxRt/$_32.JPG?set_id=880000500F
https://i.ebayimg.com/00/s/MTYwMFgxMDY2/z/uFYAAOSweutalxRw/$_32.JPG?set_id=880000500F
https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/pM4AAOSwAwpalxR3/$_32.JPG?set_id=880000500F
https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/ZiUAAOSwfNxalxR7/$_32.JPG?set_id=880000500F
https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/cl4AAOSw0kValxSD/$_32.JPG?set_id=880000500F
https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/sHkAAOSwRYFalxS2/$_32.JPG?set_id=880000500F'''
