# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20171205_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ibuyer',
            field=models.PositiveIntegerField(null=True, verbose_name='buyer ID'),
        ),
    ]
