# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_ibuyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='iitemnumb',
            new_name='iItemNumb',
        ),
        migrations.RenameField(
            model_name='itemimage',
            old_name='iitemnumb',
            new_name='iItemNumb',
        ),
        migrations.AlterUniqueTogether(
            name='itemimage',
            unique_together=set([('iItemNumb', 'isequence')]),
        ),
    ]
