# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    replaces = [('searching', '0001_initial'), ('searching', '0002_auto_20180218_1311'), ('searching', '0003_auto_20180218_1647'), ('searching', '0004_auto_20180221_1050'), ('searching', '0005_auto_20180222_2003'), ('searching', '0006_useritemfound_isearch'), ('searching', '0007_auto_20180223_2119')]

    initial = True

    dependencies = [
        ('brands', '0016_auto_20180214_0627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0026_auto_20180214_0627'),
        ('categories', '0027_auto_20180214_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFound',
            fields=[
                ('iItemNumb', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ebay item number')),
                ('cTitle', models.CharField(db_index=True, max_length=80, verbose_name='auction title')),
                ('cLocation', models.CharField(max_length=48, verbose_name='location')),
                ('cCountry', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('cMarket', models.CharField(max_length=14, verbose_name='market Global ID')),
                ('cGalleryURL', models.CharField(max_length=88, verbose_name='gallery pic URL')),
                ('cEbayItemURL', models.CharField(max_length=188, verbose_name='ebay item URL')),
                ('tTimeBeg', models.DateTimeField(null=True, verbose_name='beginning date/time')),
                ('tTimeEnd', models.DateTimeField(null=True, verbose_name='ending date/time')),
                ('bBestOfferable', models.BooleanField(default=False, verbose_name='best offer enabled?')),
                ('bBuyItNowable', models.BooleanField(default=False, verbose_name='buy it now enabled?')),
                ('cListingType', models.CharField(max_length=15, verbose_name='listing type')),
                ('dCurrentPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='current price (converted to USD)')),
                ('iCategoryID', models.PositiveIntegerField(null=True, verbose_name='primary category ID')),
                ('cCategory', models.CharField(max_length=48, verbose_name='primary category')),
                ('iConditionID', models.IntegerField(verbose_name='condition ID')),
                ('cCondition', models.CharField(max_length=28, verbose_name='condition display name')),
                ('cSellingState', models.CharField(max_length=18, verbose_name='selling state')),
                ('tCreate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created on')),
                ('lCurrentPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='current price (local currency)')),
                ('lLocalCurrency', models.CharField(default='USD', max_length=3, verbose_name='local currency')),
            ],
            options={
                'db_table': 'itemsfound',
                'verbose_name_plural': 'itemsfound',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTitle', models.CharField(max_length=38, null=True, verbose_name='short description')),
                ('cKeyWords', models.TextField(blank=True, help_text='Bot will search for these words in the auction titles -- (key words OR ebay category required!) (Including both is OK)', max_length=350, null=True, verbose_name='search for key words (maximum length 350 characters)')),
                ('iDummyCategory', models.PositiveIntegerField(blank=True, help_text='Limit search to items listed in this category -- (key words OR ebay category required!)', null=True, verbose_name='ebay category number')),
                ('cPriority', models.CharField(help_text='high priority 1 ... 9 A ... Z a ... z low priority', max_length=2, null=True, verbose_name='processing priority')),
                ('tSearchStarted', models.DateTimeField(null=True, verbose_name='last search started')),
                ('tSearchComplete', models.DateTimeField(null=True, verbose_name='last search completed')),
                ('cLastResult', models.CharField(max_length=28, null=True, verbose_name='last search outcome')),
                ('tCreate', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('tModify', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('iEbayCategory', models.ForeignKey(blank=True, help_text='Limit search to items listed in this category -- (key words OR ebay category required!) (Both are OK)', null=True, on_delete=django.db.models.deletion.CASCADE, to='ebayinfo.EbayCategory', verbose_name='ebay category (optional)')),
                ('iUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'db_table': 'searching',
                'ordering': ('cTitle',),
                'verbose_name_plural': 'searches',
            },
        ),
        migrations.AlterUniqueTogether(
            name='search',
            unique_together=set([('iUser', 'cKeyWords', 'iEbayCategory'), ('iUser', 'cTitle'), ('iUser', 'cPriority')]),
        ),
        #migrations.AlterField(
            #model_name='search',
            #name='iEbayCategory',
            #field=models.PositiveIntegerField(blank=True, help_text='Limit search to items listed in this category -- (key words OR ebay category required!) (Both are OK)', null=True, verbose_name='ebay category (optional)'),
        #),
        #migrations.AlterField(
            #model_name='search',
            #name='iEbayCategory',
            #field=models.ForeignKey(blank=True, help_text='Limit search to items listed in this category -- (key words OR ebay category required!) (Both are OK)', null=True, on_delete=django.db.models.deletion.CASCADE, to='ebayinfo.EbayCategory', verbose_name='ebay category (optional)'),
        #),
        migrations.CreateModel(
            name='UserItemFound',
            fields=[
                ('iItemNumb', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ebay item number')),
                ('dhitstars', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='hit stars')),
                ('bitemhit', models.BooleanField(default=False, verbose_name='item of interest?')),
                ('tlook4hits', models.DateTimeField(null=True, verbose_name='assessed interest date/time')),
                ('tCreate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created on')),
                ('tModify', models.DateTimeField(auto_now=True, verbose_name='retrieved info date/time')),
                ('iBrand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand')),
                ('iCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('iModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Model')),
                ('iUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('iSearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searching.Search', verbose_name='Search that first found this item')),
            ],
            options={
                'db_table': 'useritemsfound',
                'verbose_name_plural': 'useritemsfound',
            },
        ),
        migrations.AlterUniqueTogether(
            name='useritemfound',
            unique_together=set([('iItemNumb', 'iUser')]),
        ),
    ]
