# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='iEbayCategory',
            field=models.PositiveIntegerField(blank=True, help_text='Limit search to items listed in this category -- (key words OR ebay category required!) (Both are OK)', null=True, verbose_name='ebay category (optional)'),
        ),
    ]
