# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searching', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useritemfound',
            unique_together=set([('iItemNumb', 'iUser', 'iModel')]),
        ),
    ]
