# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfound',
            name='id',
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iItemNumb',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ebay item number'),
        ),
    ]
