# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0001_squashed_0007_auto_20180223_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='cCondition',
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name='condition display name'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iConditionID',
            field=models.IntegerField(blank=True, null=True, verbose_name='condition ID'),
        ),
    ]
