# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searching', '0002_auto_20180312_1844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useritemfound',
            unique_together=set([('iItemFound', 'iUser')]),
        ),
    ]
