# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_auto_20171221_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='cTitle',
            field=models.CharField(max_length=38, null=True, verbose_name='short description'),
        ),
    ]
