# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 02:17
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_auto_20180417_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfoundtemp',
            name='iStarsBrand',
            field=core.models.IntegerRangeField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='itemfoundtemp',
            name='iStarsCategory',
            field=core.models.IntegerRangeField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='itemfoundtemp',
            name='iStarsModel',
            field=core.models.IntegerRangeField(default=1, null=True),
        ),
    ]
