# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_auto_20180304_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfound',
            name='cCatHeirarchy',
            field=models.TextField(blank=True, null=True, verbose_name='category hierarchy'),
        ),
    ]
