# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_auto_20180214_0627'),
        ('brands', '0016_auto_20180214_0627'),
        ('categories', '0027_auto_20180214_0627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searching', '0003_auto_20180218_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItemFound',
            fields=[
                ('iItemNumb', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ebay item number')),
                ('dhitstars', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='hit stars')),
                ('bitemhit', models.BooleanField(default=False, verbose_name='item of interest?')),
                ('tlook4hits', models.DateTimeField(null=True, verbose_name='assessed interest date/time')),
                ('tCreate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created on')),
                ('tModify', models.DateTimeField(auto_now=True, verbose_name='retrieved info date/time')),
                ('iBrand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand')),
                ('iCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('iModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Model')),
                ('iUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'db_table': 'useritemsfound',
                'verbose_name_plural': 'useritemsfound',
            },
        ),
        migrations.RenameField(
            model_name='itemfound',
            old_name='nCurrentPrice',
            new_name='dCurrentPrice',
        ),
        migrations.RemoveField(
            model_name='itemfound',
            name='bitemhit',
        ),
        migrations.RemoveField(
            model_name='itemfound',
            name='dhitstars',
        ),
        migrations.RemoveField(
            model_name='itemfound',
            name='iBrand',
        ),
        migrations.RemoveField(
            model_name='itemfound',
            name='iCategory',
        ),
        migrations.RemoveField(
            model_name='itemfound',
            name='iModel',
        ),
        migrations.RemoveField(
            model_name='itemfound',
            name='iUser',
        ),
        migrations.RemoveField(
            model_name='itemfound',
            name='mCurrentPrice',
        ),
        migrations.RemoveField(
            model_name='itemfound',
            name='mCurrentPrice_currency',
        ),
        migrations.RemoveField(
            model_name='itemfound',
            name='tModify',
        ),
        migrations.RemoveField(
            model_name='itemfound',
            name='tlook4hits',
        ),
        migrations.AddField(
            model_name='itemfound',
            name='lCurrentPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='current price (local currency)'),
        ),
        migrations.AddField(
            model_name='itemfound',
            name='lLocalCurrency',
            field=models.CharField(default='USD', max_length=3, verbose_name='local currency'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='cTitle',
            field=models.CharField(db_index=True, max_length=80, verbose_name='auction title'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iCategoryID',
            field=models.PositiveIntegerField(null=True, verbose_name='primary category ID'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='tCreate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created on'),
        ),
        migrations.AlterUniqueTogether(
            name='useritemfound',
            unique_together=set([('iItemNumb', 'iUser')]),
        ),
    ]
