# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0003_auto_20180418_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='cTitle',
            field=models.CharField(max_length=80, verbose_name='item title'),
        ),
    ]
