# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_auto_20180214_0627'),
        ('categories', '0027_auto_20180214_0627'),
        ('brands', '0016_auto_20180214_0627'),
        ('searching', '0003_auto_20180312_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFoundTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhitstars', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='hit stars')),
                ('iBrand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand')),
                ('iCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
            options={
                'verbose_name_plural': 'itemsfoundtemp',
                'db_table': 'itemsfoundtemp',
            },
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iMarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebayinfo.Market', verbose_name='ebay site ID'),
        ),
        migrations.AddField(
            model_name='itemfoundtemp',
            name='iItemFound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searching.ItemFound'),
        ),
        migrations.AddField(
            model_name='itemfoundtemp',
            name='iModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Model'),
        ),
        migrations.AddField(
            model_name='itemfoundtemp',
            name='iSearch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searching.Search', verbose_name='Search that first found this item'),
        ),
    ]
