# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0004_auto_20180308_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='c2ndCategory',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='secondary category (optional)'),
        ),
    ]
