# Generated by Django 2.2.10 on 2020-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0004_auto_20200104_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='bGetBuyItNows',
            field=models.NullBooleanField(default=False, help_text='You may get an avalanche of useless junk auctionsif you turn this on -- be careful!', verbose_name='get BuyItNow auctions?'),
        ),
    ]
