# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 06:05
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searching', '0004_auto_20180315_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemfoundtemp',
            old_name='iItemFound',
            new_name='iItemNumb',
        ),
        migrations.RenameField(
            model_name='useritemfound',
            old_name='iItemFound',
            new_name='iItemNumb',
        ),
        migrations.RemoveField(
            model_name='itemfoundtemp',
            name='dhitstars',
        ),
        migrations.AddField(
            model_name='itemfoundtemp',
            name='cWhereCategory',
            field=models.CharField(max_length=10, null=True, verbose_name='where category was found'),
        ),
        migrations.AddField(
            model_name='itemfoundtemp',
            name='iHitStars',
            field=core.models.IntegerRangeField(default=0, null=True, verbose_name='hit stars'),
        ),
        migrations.AddField(
            model_name='useritemfound',
            name='cWhereCategory',
            field=models.CharField(max_length=10, null=True, verbose_name='where category was found'),
        ),
        migrations.AddField(
            model_name='useritemfound',
            name='iHitStars',
            field=core.models.IntegerRangeField(default=0, null=True, verbose_name='hit stars'),
        ),
        migrations.RemoveField(
            model_name='useritemfound',
            name='dhitstars',
        ),
        migrations.AlterUniqueTogether(
            name='useritemfound',
            unique_together=set([('iItemNumb', 'iUser')]),
        ),
    ]
