# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0004_auto_20171223_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='cKeyWords',
            field=models.TextField(max_length=350, verbose_name='search for key words (maximum length 350 characters)'),
        ),
    ]
