# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0004_auto_20180221_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='cCategory',
            field=models.CharField(max_length=48, verbose_name='primary category'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='cCondition',
            field=models.CharField(max_length=28, verbose_name='condition display name'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='cCountry',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='cEbayItemURL',
            field=models.CharField(max_length=188, verbose_name='ebay item URL'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='cGalleryURL',
            field=models.CharField(max_length=88, verbose_name='gallery pic URL'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='cListingType',
            field=models.CharField(max_length=15, verbose_name='listing type'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='cLocation',
            field=models.CharField(max_length=48, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='cMarket',
            field=models.CharField(max_length=14, verbose_name='market Global ID'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='cSellingState',
            field=models.CharField(max_length=18, verbose_name='selling state'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='dCurrentPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='current price (converted to USD)'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iConditionID',
            field=models.IntegerField(verbose_name='condition ID'),
        ),
    ]
