# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0005_auto_20171225_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='iDummyCategory',
            field=models.PositiveIntegerField(blank=True, help_text='Limit search to items listed in this category -- (key words OR ebay category required!)', null=True, verbose_name='ebay category number'),
        ),
        migrations.AlterField(
            model_name='search',
            name='cKeyWords',
            field=models.TextField(blank=True, help_text='Bot will search for these words in the auction titles -- (key words OR ebay category required!)', max_length=350, null=True, verbose_name='search for key words (maximum length 350 characters)'),
        ),
        migrations.AlterField(
            model_name='search',
            name='cPriority',
            field=models.CharField(help_text='1 is higher than 9, 9 is higher than A, A is higher than a', max_length=2, null=True, verbose_name='processing priority'),
        ),
        migrations.AlterField(
            model_name='search',
            name='iEbayCategory',
            field=models.ForeignKey(blank=True, help_text='Limit search to items listed in this category -- (key words OR ebay category required!)', null=True, on_delete=django.db.models.deletion.CASCADE, to='ebaycategories.EbayCategory', verbose_name='ebay category (optional)'),
        ),
    ]
