# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebayinfo', '0007_auto_20180311_0948'),
        ('searching', '0005_auto_20180308_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfound',
            name='cCatHeirarchy',
        ),
        migrations.AddField(
            model_name='itemfound',
            name='i2ndCatHeirarchy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_category', to='ebayinfo.CategoryHierarchy', verbose_name='category hierarchy (secondary)'),
        ),
        migrations.AddField(
            model_name='itemfound',
            name='iCatHeirarchy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_category', to='ebayinfo.CategoryHierarchy', verbose_name='category hierarchy (primary)'),
        ),
    ]
