# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0005_auto_20180425_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='i2ndCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebay_secondary_category', to='ebayinfo.EbayCategory', verbose_name='secondary category ID (optional)'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebay_primary_category', to='ebayinfo.EbayCategory', verbose_name='primary category ID'),
        ),
    ]
