# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0005_auto_20180315_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfoundtemp',
            name='cWhereCategory',
            field=models.CharField(default='title', max_length=10, verbose_name='where category was found'),
        ),
        migrations.AlterField(
            model_name='useritemfound',
            name='cWhereCategory',
            field=models.CharField(default='title', max_length=10, verbose_name='where category was found'),
        ),
    ]
