# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import searching.validators


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0006_auto_20180116_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='cKeyWords',
            field=models.TextField(blank=True, help_text='Bot will search for these words in the auction titles -- (key words OR ebay category required!) (Both are OK)', max_length=350, null=True, verbose_name='search for key words (maximum length 350 characters)'),
        ),
        migrations.AlterField(
            model_name='search',
            name='cPriority',
            field=models.CharField(help_text='high priority 1 ... 9 A ... Z a ... z low priority', max_length=2, null=True, verbose_name='processing priority'),
        ),
        migrations.AlterField(
            model_name='search',
            name='iDummyCategory',
            field=models.PositiveIntegerField(blank=True, help_text='Limit search to items listed in this category -- (key words OR ebay category required!)', null=True, validators=[searching.validators.require_digits_only], verbose_name='ebay category number'),
        ),
        migrations.AlterField(
            model_name='search',
            name='iEbayCategory',
            field=models.ForeignKey(blank=True, help_text='Limit search to items listed in this category -- (key words OR ebay category required!) (Both are OK)', null=True, on_delete=django.db.models.deletion.CASCADE, to='ebaycategories.EbayCategory', verbose_name='ebay category (optional)'),
        ),
    ]
