# Generated by Django 2.2.10 on 2020-04-27 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20200104_2144'),
        ('searching', '0006_auto_20200421_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='iMyCategory',
            field=models.ForeignKey(blank=True, help_text='Example: if you have a category for "manuals" and this search is in the ebay category "Vintage Manuals" put your "manuals" category here.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category', verbose_name='ebay category matches my category'),
        ),
        migrations.AlterField(
            model_name='search',
            name='bInventory',
            field=models.NullBooleanField(default=False, help_text='You may get an avalanche of useless junk if you turn this on -- be careful!', verbose_name="also get 'Store Inventory' (fixed price items in ebay stores)?"),
        ),
        migrations.AlterField(
            model_name='search',
            name='cKeyWords',
            field=models.TextField(blank=True, help_text='What you type here will go into the ebay search box -- mulitple terms will result in an AND search (ebay will look for all terms).<br>search for red OR green handbags as follows: handbags (red,green)<br>TIPS: to exclude words, put a - in front (without any space),<br>search handbags but exclude red as follows: handbags -red<br>search for handbags but exclude red and green as follows: handbags -red -green', max_length=350, null=True, verbose_name='key words -- search for these (maximum length 350 characters)'),
        ),
        migrations.AlterField(
            model_name='search',
            name='cTitle',
            field=models.CharField(help_text='This is just a short description -- ebay will not search for this<br>you must have a) key word(s) and/or b) an ebay category', max_length=38, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='search',
            name='iDummyCategory',
            field=models.PositiveIntegerField(blank=True, help_text='Limit search to items listed in this category<br>copy the category number from ebay and paste here!!! (sorry)', null=True, verbose_name='ebay category number'),
        ),
        migrations.AlterField(
            model_name='search',
            name='iEbayCategory',
            field=models.ForeignKey(blank=True, help_text='Limit search to items listed in this category', null=True, on_delete=django.db.models.deletion.CASCADE, to='ebayinfo.EbayCategory', verbose_name='ebay category'),
        ),
    ]
