# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0006_useritemfound_isearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritemfound',
            name='iSearch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searching.Search', verbose_name='Search that first found this item'),
        ),
    ]
