# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0006_auto_20180429_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='i2ndCategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebay_secondary_category', to='ebayinfo.EbayCategory', verbose_name='secondary category ID (optional)'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_primary_category', to='ebayinfo.EbayCategory', verbose_name='primary category ID'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='lCurrentPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='current price'),
        ),
    ]
