# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 04:24
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0006_auto_20180316_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritemfound',
            name='iHitStars',
            field=core.models.IntegerRangeField(db_index=True, default=0, null=True, verbose_name='hit stars'),
        ),
    ]
