# Generated by Django 2.2.10 on 2020-05-03 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0007_auto_20200427_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='iMyCategory',
            field=models.ForeignKey(blank=True, help_text='Example: if you have a category for "Manuals" and this search is in the ebay category "Vintage Manuals" put your "Manuals" category here.<br>If you have a category "Widgets" and this search finds an item with "Widget Manual" in the title, the bot will know this item is for a manual, NOT a widget.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category', verbose_name='my category that matches ebay category'),
        ),
    ]
