# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import searching.validators


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0007_auto_20180116_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='iEbayCategory',
            field=models.ForeignKey(blank=True, help_text='Limit search to items listed in this category -- (key words OR ebay category required!) (Both are OK)', null=True, on_delete=django.db.models.deletion.CASCADE, to='ebaycategories.EbayCategory', validators=[searching.validators.require_digits_only], verbose_name='ebay category (optional)'),
        ),
    ]
