# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0007_auto_20180317_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tSearchTime', models.DateTimeField(db_index=True, verbose_name='search date')),
                ('iItems', models.PositiveIntegerField(verbose_name='items found')),
                ('iStoreItems', models.PositiveIntegerField(verbose_name='items stored')),
                ('iStoreUsers', models.PositiveIntegerField(verbose_name='items stored for owner')),
                ('iSearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searching.Search', verbose_name='Search that first found this item')),
            ],
            options={
                'verbose_name_plural': 'searchlogs',
                'db_table': 'searchlogs',
            },
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='tCreate',
            field=models.DateTimeField(db_index=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='useritemfound',
            name='tCreate',
            field=models.DateTimeField(db_index=True, verbose_name='created on'),
        ),
    ]
