# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0007_auto_20180430_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='iCategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebay_primary_category', to='ebayinfo.EbayCategory', verbose_name='primary category ID'),
        ),
    ]
