# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0017_auto_20180102_1020'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searching', '0008_auto_20180116_2326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='search',
            unique_together=set([('iUser', 'cPriority'), ('cKeyWords', 'iEbayCategory')]),
        ),
    ]
