# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0008_auto_20180430_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritemfound',
            name='bGetPictures',
            field=models.BooleanField(default=False, verbose_name='get description & pictures?'),
        ),
        migrations.AlterField(
            model_name='useritemfound',
            name='tModify',
            field=models.DateTimeField(auto_now=True, verbose_name='updated on'),
        ),
    ]
