# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0008_auto_20180325_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='cGalleryURL',
            field=models.CharField(blank=True, max_length=88, null=True, verbose_name='gallery pic URL'),
        ),
    ]
