# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0009_auto_20180501_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfound',
            name='tRetrieved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retrieved info'),
        ),
        migrations.AddField(
            model_name='useritemfound',
            name='tRetrieved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retrieved info'),
        ),
    ]
