# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0009_auto_20180327_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='i2ndCatHeirarchy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='category hierarchy (secondary)'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iCatHeirarchy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='category hierarchy (primary)'),
        ),
    ]
