# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebaycategories', '0017_auto_20180102_1020'),
        ('searching', '0009_auto_20180123_0454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='search',
            unique_together=set([('iUser', 'cKeyWords', 'iEbayCategory'), ('iUser', 'cTitle'), ('iUser', 'cPriority')]),
        ),
    ]
