# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0010_auto_20180501_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfound',
            name='tRetrieveFinal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retrieved info after end'),
        ),
        migrations.AddField(
            model_name='useritemfound',
            name='tRetrieveFinal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retrieved info after end'),
        ),
    ]
