# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0010_auto_20180327_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='i2ndCatHeirarchy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_category', to='ebayinfo.CategoryHierarchy', verbose_name='category hierarchy (secondary)'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='iCatHeirarchy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_category', to='ebayinfo.CategoryHierarchy', verbose_name='category hierarchy (primary)'),
        ),
    ]
