# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0010_auto_20180123_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ('cTitle',), 'verbose_name_plural': 'searches'},
        ),
    ]
