# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0012_auto_20180515_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfound',
            name='bCancelledItem',
            field=models.BooleanField(default=False, verbose_name='Invalid Or Non-Existent Item Number'),
        ),
    ]
