# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0012_auto_20180327_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='iEbaySiteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebayinfo.Market', verbose_name='ebay site ID (PK)'),
        ),
    ]
