# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0013_auto_20180327_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='cLastResult',
            field=models.TextField(null=True, verbose_name='last search outcome'),
        ),
    ]
