# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0013_auto_20180130_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='iUser',
        ),
        migrations.DeleteModel(
            name='FoundItem',
        ),
    ]
