# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0013_itemfound_bcancelleditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfoundtemp',
            name='tLook4Hits',
            field=models.DateTimeField(null=True, verbose_name='assessed interest date/time'),
        ),
    ]
