# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0014_auto_20180327_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='cResult',
            field=models.TextField(null=True, verbose_name='search outcome'),
        ),
    ]
