# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0014_itemfoundtemp_tlook4hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfoundtemp',
            name='tLook4Hits',
        ),
    ]
