# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0015_searchlog_cresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchlog',
            old_name='tSearchTime',
            new_name='tSearchStarted',
        ),
    ]
