# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0015_founditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='founditem',
            options={'verbose_name_plural': 'founditems'},
        ),
        migrations.AlterModelTable(
            name='founditem',
            table='founditems',
        ),
    ]
