# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0015_remove_itemfoundtemp_tlook4hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritemfound',
            name='bAuction',
            field=models.BooleanField(default=False, verbose_name='Auction or Auction with Buy It Now'),
        ),
    ]
