# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0016_auto_20180130_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='tLastSearch',
        ),
        migrations.AddField(
            model_name='search',
            name='tSearchComplete',
            field=models.DateTimeField(null=True, verbose_name='last search completed'),
        ),
        migrations.AddField(
            model_name='search',
            name='tSearchStarted',
            field=models.DateTimeField(null=True, verbose_name='last search started'),
        ),
    ]
