# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0016_auto_20180329_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='iItemHits',
            field=models.PositiveIntegerField(null=True, verbose_name='items with category, brand & model'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='tSearchComplete',
            field=models.DateTimeField(null=True, verbose_name='last search completed'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='tSearchStarted',
            field=models.DateTimeField(db_index=True, verbose_name='search started'),
        ),
    ]
