# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0016_useritemfound_bauction'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfoundtemp',
            name='iFoundModelLen',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
