# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0017_auto_20180205_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='iUser',
        ),
        migrations.AlterField(
            model_name='search',
            name='cKeyWords',
            field=models.TextField(blank=True, help_text='Bot will search for these words in the auction titles -- (key words OR ebay category required!) (Including both is OK)', max_length=350, null=True, verbose_name='search for key words (maximum length 350 characters)'),
        ),
        migrations.DeleteModel(
            name='FoundItem',
        ),
    ]
