# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0018_auto_20180331_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='tSearchBeg',
            new_name='tBegSearch',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='tSearchEnd',
            new_name='tEndSearch',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='tSearchBeg',
            new_name='tBegSearch',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='tSearchEnd',
            new_name='tEndSearch',
        ),
        migrations.AddField(
            model_name='searchlog',
            name='tBegStore',
            field=models.DateTimeField(null=True, verbose_name='search professing started'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='tEndStore',
            field=models.DateTimeField(null=True, verbose_name='search professing completed'),
        ),
    ]
