# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
        ('models', '0002_auto_20181216_0720'),
        ('searching', '0018_itemfound_csubtitle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useritemfound',
            unique_together=set([('iItemNumb', 'iUser', 'iModel', 'iBrand')]),
        ),
    ]
