# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0019_auto_20181216_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='cKeyWords',
            field=models.TextField(blank=True, help_text='What you type here will go into the ebay serch box -- mulitple terms will result in an AND search.  TIPS: to exclude words, put a - in front (without any space), search for red OR green handbags as follows: handbags (red,green)  search for handbags but exclude red and green as follows: handbags -(red,green)  350 characters MAX', max_length=350, null=True, verbose_name='search for key words (maximum length 350 characters)'),
        ),
    ]
