# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0019_auto_20180331_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='cPriority',
            field=models.CharField(help_text='high priority A1 A2 A3 ... Z9 low priority', max_length=2, null=True, verbose_name='processing priority'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='iItemHits',
            field=models.PositiveIntegerField(null=True, verbose_name='have category, brand & model'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='iStoreUsers',
            field=models.PositiveIntegerField(null=True, verbose_name='stored for owner'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='tBegStore',
            field=models.DateTimeField(null=True, verbose_name='processing started'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='tEndSearch',
            field=models.DateTimeField(null=True, verbose_name='search completed'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='tEndStore',
            field=models.DateTimeField(null=True, verbose_name='processing completed'),
        ),
    ]
