# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0019_itemfound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfound',
            name='iBidCount',
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='cListingType',
            field=models.CharField(max_length=15, null=True, verbose_name='listing type'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='dhitstars',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='hit stars'),
        ),
    ]
