# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0020_auto_20180401_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritemfound',
            name='bitemhit',
        ),
        migrations.AddField(
            model_name='useritemfound',
            name='bGetDescribe',
            field=models.BooleanField(default=False, verbose_name='get description?'),
        ),
        migrations.AddField(
            model_name='useritemfound',
            name='bGetPictures',
            field=models.BooleanField(default=False, verbose_name='get pictures?'),
        ),
        migrations.AlterField(
            model_name='itemfound',
            name='lCurrentPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='current price'),
        ),
        migrations.AlterField(
            model_name='useritemfound',
            name='iBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='useritemfound',
            name='iCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='useritemfound',
            name='iModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Model', verbose_name='Model Name/Number'),
        ),
    ]
