# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0021_auto_20180404_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritemfound',
            name='bListExclude',
            field=models.BooleanField(default=False, verbose_name='exclude from listing?'),
        ),
    ]
