# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0021_itemfound_ishippingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfound',
            name='iShippingType',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Calculated'), (1, 'Calculated Domestic Flat International'), (2, 'Flat'), (3, 'Flat Domestic Calculated International'), (4, 'Free'), (5, 'Free Pick up'), (6, 'Freight'), (7, 'Freight Flat'), (8, 'Not Specified')], null=True, verbose_name='shipping type'),
        ),
    ]
