# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0022_useritemfound_blistexclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritemfound',
            name='tGotPics',
            field=models.DateTimeField(blank=True, null=True, verbose_name='got pictures'),
        ),
    ]
