# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0023_useritemfound_tgotpics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritemfound',
            name='bGetDescribe',
        ),
    ]
