# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 04:07
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bwanted', models.BooleanField(default=True, verbose_name='want this combination?')),
                ('tcreate', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('ibrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.Brand')),
            ],
            options={
                'verbose_name_plural': 'brandcategories',
                'db_table': 'brandcategories',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(db_index=True, max_length=48, verbose_name='category description')),
                ('ckeywords', models.CharField(max_length=88, verbose_name='category key words')),
                ('bkeywordrequired', models.BooleanField(default=True, verbose_name='key word required?')),
                ('istars', core.models.IntegerRangeField(verbose_name='desireability, 10 star category is most desireable')),
                ('ballofinterest', models.BooleanField(default=True, verbose_name='want everything of this category?')),
                ('bwantpair', models.BooleanField(default=False, verbose_name='only want pairs?')),
                ('baccessory', models.BooleanField(default=False, verbose_name='accessory?')),
                ('bcomponent', models.BooleanField(default=False, verbose_name='component?')),
                ('ccomment', models.TextField(null=True, verbose_name='comments')),
                ('cnationality', django_countries.fields.CountryField(max_length=2, null=True)),
                ('ilegacykey', models.PositiveIntegerField(unique=True, verbose_name='legacy key')),
                ('clegacyfamily', models.PositiveIntegerField(null=True, verbose_name='legacy family')),
                ('tlegacycreate', models.DateTimeField(verbose_name='legacy row created on')),
                ('tlegacymodify', models.DateTimeField(verbose_name='legacy row updated on')),
                ('tcreate', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('tmodify', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('ifamily', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('iuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('ctitle',),
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='icategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='iuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
