# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='clegacyfamily',
            new_name='ilegacyfamily',
        ),
    ]
