# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Put nick names, common misspellings and alternate category names here -- leave blank if Bot only needs to look for the category name.<br>Each line is evaluated separately, Bot will know item is in this category if any one line matches.<br/>No need for plural words: plural forms of common words in descriptioon or here will also be found.', null=True, verbose_name='Considered a hit if this text is found (optional)'),
        ),
    ]
