# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20171111_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tlegacymodify',
            field=models.DateTimeField(null=True, verbose_name='legacy row updated on'),
        ),
    ]
