# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-26 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20191107_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cKeyWords',
            field=models.TextField(blank=True, help_text='Putting text here is optional, but if there is text here, robot will consider it REQUIRED -- must be found in the title or category heirachy <b>IN ADDITION TO</b> category name.<br>Put alternate key words on separate lines -- Bot will know item is for this category if words on any one line match.', null=True, verbose_name='category key words'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Put nick names, common misspellings and alternate category names here -- leave blank if Bot only needs to look for the category name.<br>Each line is evaluated separately, Bot will know item is in this category if any one line matches.<br/>No need for plural words: plural forms of common words in name or here will also be found.', null=True, verbose_name='Considered a hit if this text is found (optional -- if you include, bot will also search for this)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cTitle',
            field=models.CharField(db_index=True, help_text='Put the category name here -- Bot will search for this in the auction title <em>AND</em> category heirachy for each item found.<br/>Optionally, you can put additional description in parentheses ().  While searching auction titles, bot will ignore anything in parentheses.', max_length=48, verbose_name='category name'),
        ),
    ]
