# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20171111_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ccomment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cnationality',
        ),
    ]
