# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 23:34
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20171111_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ballofinterest',
            field=models.BooleanField(default=False, verbose_name='want everything of this category?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='bkeywordrequired',
            field=models.BooleanField(default=False, verbose_name='key word required?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ckeywords',
            field=models.CharField(max_length=88, null=True, verbose_name='category key words'),
        ),
        migrations.AlterField(
            model_name='category',
            name='istars',
            field=core.models.IntegerRangeField(default=5, verbose_name='desireability, 10 star category is most desireable'),
        ),
    ]
