# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-04 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20191226_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cLookFor',
            field=models.TextField(blank=True, help_text="Put nick names, common misspellings and alternate category names here -- leave blank if Bot only needs to look for the category name.<br>For example, if the category is widget <em>tester</em>, put 'widget <em>testor</em>' here<br>Each line is evaluated separately, Bot will know item is in this category if any one line matches.<br/>No need for plural words: plural forms of common words in name or here will also be found.", null=True, verbose_name='Considered a hit if this text is found (optional -- if you include, bot will also search for this)'),
        ),
    ]
