# Generated by Django 3.2.4 on 2021-08-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20200104_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bModelsByYear',
            field=models.BooleanField(default=False, help_text='examples: automobiles, guitars', verbose_name='do models vary by year?'),
        ),
    ]
