# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20171114_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ckeywords',
            field=models.CharField(blank=True, max_length=88, null=True, verbose_name='category key words'),
        ),
    ]
