# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20171114_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcategory',
            options={'verbose_name_plural': 'BrandCategories'},
        ),
        migrations.AlterModelTable(
            name='brandcategory',
            table='BrandCategories',
        ),
    ]
