# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20171124_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cexcludeif',
            field=models.TextField(blank=True, null=True, verbose_name='not a hit if this text is found'),
        ),
    ]
