# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_category_cexcludeif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ifamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
