# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_auto_20171205_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ifamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='category family'),
        ),
    ]
