# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_auto_20171204_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('cTitle',), 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='brandcategory',
            old_name='bwanted',
            new_name='bWant',
        ),
        migrations.RenameField(
            model_name='brandcategory',
            old_name='ibrand',
            new_name='iBrand',
        ),
        migrations.RenameField(
            model_name='brandcategory',
            old_name='icategory',
            new_name='iCategory',
        ),
        migrations.RenameField(
            model_name='brandcategory',
            old_name='iuser',
            new_name='iUser',
        ),
        migrations.RenameField(
            model_name='brandcategory',
            old_name='tcreate',
            new_name='tCreate',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='baccessory',
            new_name='bAccessory',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ballofinterest',
            new_name='bAllOfInterest',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='bcomponent',
            new_name='bComponent',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='bkeywordrequired',
            new_name='bKeyWordRequired',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='bwantpair',
            new_name='bWantPair',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cexcludeif',
            new_name='cExcludeIf',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ckeywords',
            new_name='cKeyWords',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ctitle',
            new_name='cTitle',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ifamily',
            new_name='iFamily',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ilegacyfamily',
            new_name='iLegacyFamily',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ilegacykey',
            new_name='iLegacyKey',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='istars',
            new_name='iStars',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='iuser',
            new_name='iUser',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tcreate',
            new_name='tCreate',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tlegacycreate',
            new_name='tLegacyCreate',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tlegacymodify',
            new_name='tLegacyModify',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tmodify',
            new_name='tModify',
        ),
    ]
