# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_category_clookfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bModelsShared',
            field=models.BooleanField(default=False, verbose_name='brands share model numbers'),
        ),
    ]
