# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0018_auto_20180119_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tLegacyCreate',
            field=models.DateTimeField(null=True, verbose_name='legacy row created on'),
        ),
    ]
