# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0019_auto_20180119_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bWantPair',
            field=models.BooleanField(default=False, help_text='are you hoping to find these in paris?', verbose_name='prefer pairs?'),
        ),
    ]
