# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 04:12
from __future__ import unicode_literals

from django.db import migrations, models
#import regex_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0020_auto_20180125_0119'),
    ]

    operations = [
        #migrations.AddField(
            #model_name='category',
            #name='oRegEx',
            #field=regex_field.fields.RegexField(max_length=128, null=True),
        #),
        migrations.AlterField(
            model_name='category',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Considered a hit if this text is found -- leave blank if bot only needs to look for the category name. Each line evaluated separately, put different look for tests on different lines.', null=True, verbose_name='Considered a hit if this text is found'),
        ),
    ]
