# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0021_auto_20180126_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='oRegEx',
            new_name='oRegExFound',
        ),
        migrations.AlterField(
            model_name='category',
            name='cKeyWords',
            field=models.CharField(blank=True, help_text='Bot will look for this text in the item description; note: anything in parentheses (), bot will ignore', max_length=88, null=True, verbose_name='category key words'),
        ),
    ]
