# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0023_category_oregexexclude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bKeyWordRequired',
        ),
        migrations.AlterField(
            model_name='category',
            name='cKeyWords',
            field=models.TextField(blank=True, help_text='Words that must be found in the title <em>IN ADDITION TO</em> category name.Put alternate key words on separate lines -- Bot will know item is for in this category if words on any one line match.', null=True, verbose_name='category key words (optional)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Leave blank if bot only needs to look for the category name. Each line evaluated separately, put common misspellings and alternate names here.', null=True, verbose_name='Considered a hit if this text is found (optional)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cTitle',
            field=models.CharField(db_index=True, help_text='while searching auction titles, note: bot will ignore anything in parentheses ()', max_length=48, verbose_name='category description'),
        ),
    ]
