# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models
# import regex_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0024_auto_20180128_2235'),
    ]

    operations = [
        #migrations.AddField(
            #model_name='category',
            #name='oRegExKeyWords',
            #field=regex_field.fields.RegexField(max_length=128, null=True),
        #),
        migrations.AlterField(
            model_name='category',
            name='cExcludeIf',
            field=models.TextField(blank=True, help_text='Bot will know item is <b>NOT</b> in this category if any one line matches (each line evaluated separately, put different exclude tests on different lines)', null=True, verbose_name='Not a hit if this text is found (optional)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cKeyWords',
            field=models.TextField(blank=True, help_text='Words that must be found in the title <b>IN ADDITION TO</b> category name.  Put alternate key words on separate lines -- Bot will know item is for in this category if words on any one line match.', null=True, verbose_name='category key words (optional)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cLookFor',
            field=models.TextField(blank=True, help_text='Put common misspellings and alternate names here -- leave blank if bot only needs to look for the category name. Each line evaluated separately, Bot will know item is in this category if any one line matches.', null=True, verbose_name='Considered a hit if this text is found (optional)'),
        ),
    ]
