# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0027_auto_20180214_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='oRegExExclude',
        ),
        migrations.RemoveField(
            model_name='category',
            name='oRegExKeyWords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='oRegExLook4Title',
        ),
        migrations.AddField(
            model_name='category',
            name='sRegExExclude',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sRegExLook4Title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
