# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0028_auto_20180316_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sRegExKeyWords',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
