# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0029_category_sregexkeywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sRegExExclude',
            field=models.TextField(null=True),
        ),
    ]
