# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0031_auto_20180320_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sRegExExclude',
            new_name='cRegExExclude',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='sRegExKeyWords',
            new_name='cRegExKeyWords',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='sRegExLook4Title',
            new_name='cRegExLook4Title',
        ),
    ]
