# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171231_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cBio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Bio info'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cLocation',
            field=models.CharField(blank=True, max_length=30, verbose_name='Location'),
        ),
    ]
