# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180102_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iMarket',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='markets.Market', verbose_name='ebay market (default)'),
        ),
    ]
