# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180107_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iMarket',
            field=models.PositiveIntegerField(default=1, verbose_name='ebay market (default)'),
        ),
    ]
