# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180218_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iMarket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ebayinfo.Market', verbose_name='ebay market (default)'),
        ),
    ]
