# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 23:13
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180311_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zTimeZone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
