# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_ztimezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='iMarket',
            new_name='iEbaySiteID',
        ),
    ]
