# Generated by Django 3.2.4 on 2021-07-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201225_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cCollection',
            field=models.CharField(blank=True, help_text='describe the collectables you are tracking', max_length=80, verbose_name='Collection'),
        ),
    ]
