# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name_plural': 'ebay condition descriptions'},
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='cTitle',
            new_name='ctitle',
        ),
    ]
