# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0002_auto_20171219_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='ctitle',
            new_name='cTitle',
        ),
        migrations.RenameField(
            model_name='ebaycategory',
            old_name='bleaf_category',
            new_name='bLeafCategory',
        ),
        migrations.RenameField(
            model_name='ebaycategory',
            old_name='ctitle',
            new_name='cTitle',
        ),
        migrations.RenameField(
            model_name='ebaycategory',
            old_name='ilevel',
            new_name='iLevel',
        ),
        migrations.RenameField(
            model_name='ebaycategory',
            old_name='iparent_id',
            new_name='iParent_ID',
        ),
        migrations.RenameField(
            model_name='ebaycategory',
            old_name='isupercededby',
            new_name='iSupercededBy',
        ),
    ]
