# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_auto_20171220_1249'),
        ('ebaycategories', '0003_auto_20171219_1542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ebaycategory',
            unique_together=set([('ebay_id', 'iMarket')]),
        ),
    ]
