# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0012_auto_20171220_1319'),
        ('ebaycategories', '0004_auto_20171220_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='ebay_id',
            new_name='iConditionID',
        ),
        migrations.RenameField(
            model_name='ebaycategory',
            old_name='ebay_id',
            new_name='iCategoryID',
        ),
        migrations.AlterUniqueTogether(
            name='ebaycategory',
            unique_together=set([('iCategoryID', 'iMarket')]),
        ),
    ]
