# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0005_auto_20171220_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaycategory',
            name='iParent_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentcategory', to='ebaycategories.EbayCategory', verbose_name='parent category'),
        ),
    ]
