# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0006_auto_20171220_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaycategory',
            name='cTitle',
            field=models.CharField(max_length=50, verbose_name='ebay category description'),
        ),
    ]
