# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0007_auto_20171220_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebaycategory',
            options={'ordering': ('iMarket', 'iCategoryID'), 'verbose_name_plural': 'ebay categories'},
        ),
    ]
