# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0008_auto_20171221_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaycategory',
            name='iLevel',
            field=models.PositiveSmallIntegerField(verbose_name='level (top is 1, lower levels are bigger numbers)'),
        ),
    ]
