# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0009_auto_20171223_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebaycategory',
            name='iParent_ID',
        ),
        migrations.AddField(
            model_name='ebaycategory',
            name='iParent',
            field=models.BigIntegerField(null=True, verbose_name='ebay parent category'),
        ),
        migrations.AlterField(
            model_name='ebaycategory',
            name='iLevel',
            field=models.PositiveSmallIntegerField(verbose_name='ebay level (top is 1, lower levels are bigger numbers)'),
        ),
        migrations.AlterField(
            model_name='ebaycategory',
            name='iSupercededBy',
            field=models.BigIntegerField(null=True, verbose_name='superceded by this ebay category'),
        ),
    ]
