# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0011_auto_20171229_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaycategory',
            name='iCategoryID',
            field=models.PositiveIntegerField(verbose_name='ebay category number'),
        ),
        migrations.AlterField(
            model_name='ebaycategory',
            name='iParent',
            field=models.PositiveIntegerField(null=True, verbose_name='ebay parent category'),
        ),
        migrations.AlterField(
            model_name='ebaycategory',
            name='iSupercededBy',
            field=models.PositiveIntegerField(null=True, verbose_name='superceded by this ebay category'),
        ),
    ]
