# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0012_auto_20171229_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebaycategory',
            old_name='iParent',
            new_name='iParentID',
        ),
    ]
