# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0014_auto_20171229_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebaycategory',
            options={'verbose_name_plural': 'ebay categories'},
        ),
        migrations.AlterField(
            model_name='ebaycategory',
            name='iCategoryID',
            field=models.PositiveIntegerField(db_index=True, verbose_name='ebay category number'),
        ),
    ]
