# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0015_auto_20171229_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebaycategory',
            old_name='cTitle',
            new_name='name',
        ),
    ]
