# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaycategories', '0016_auto_20171230_1223'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ebaycategory',
            table='ebay_categories',
        ),
    ]
