# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dCurrentPrice',
            new_name='dConvertPrice',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='lCurrentPrice',
            new_name='lLocalPrice',
        ),
        migrations.AddField(
            model_name='item',
            name='bBuyItNowable',
            field=models.BooleanField(default=False, verbose_name='buy it now enabled?'),
        ),
    ]
