# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20180429_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cBidCurrency',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True, verbose_name='bid currency'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cBuyItNowConvert',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True, verbose_name='buy it now local currency converted to this'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lBuyItNowCurrenc',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True, verbose_name='buy it now local currency'),
        ),
    ]
