# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20180430_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cPostalCode',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='postal code'),
        ),
    ]
