# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20180517_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cShipToLocations',
            field=models.TextField(verbose_name='ship to locations'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dMinimumBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum Bid'),
        ),
    ]
