# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20180603_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iHitCount',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Hit Count'),
        ),
    ]
