# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20180615_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cSite',
            field=models.CharField(max_length=14, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tCreate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created on'),
        ),
    ]
