# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iItemNumb', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ebay item number')),
                ('cDescription', models.TextField(verbose_name='description')),
                ('bBestOfferable', models.BooleanField(default=False, verbose_name='buy it now enabled?')),
                ('tTimeBeg', models.DateTimeField(null=True, verbose_name='beginning date/time')),
                ('tTimeEnd', models.DateTimeField(null=True, verbose_name='ending date/time')),
                ('cEbayItemURL', models.CharField(max_length=188, verbose_name='ebay item URL')),
                ('cListingType', models.CharField(max_length=15, verbose_name='listing type')),
                ('cLocation', models.CharField(max_length=48, verbose_name='location')),
                ('cPaymentMethods', models.CharField(max_length=88, verbose_name='ebay item URL')),
                ('cGalleryURL', models.CharField(blank=True, max_length=88, null=True, verbose_name='gallery pic URL')),
                ('cPictureURLs', models.TextField(blank=True, null=True, verbose_name='picture URLs')),
                ('cPostalCode', models.CharField(max_length=12, verbose_name='postal code')),
                ('iCategoryID', models.PositiveIntegerField(null=True, verbose_name='primary category ID')),
                ('cCategory', models.CharField(max_length=48, verbose_name='primary category')),
                ('iQuantity', models.SmallIntegerField(verbose_name='quantity')),
                ('cSellerID', models.CharField(max_length=48, verbose_name='seller user name')),
                ('iFeedbackScore', models.SmallIntegerField(verbose_name='seller feedback score')),
                ('cFeedbackPercent', models.CharField(max_length=8, verbose_name='seller feedback percent')),
                ('iBidCount', models.SmallIntegerField(verbose_name='bid count')),
                ('dCurrentPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='current price (converted)')),
                ('dConvertCurrency', models.CharField(default='USD', max_length=3, verbose_name='local currency converted to this')),
                ('lCurrentPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='current price (local currency)')),
                ('lLocalCurrency', models.CharField(default='USD', max_length=3, verbose_name='local currency')),
                ('cHighBidder', models.CharField(max_length=48, verbose_name='high bidder user name')),
                ('cListingStatus', models.CharField(max_length=18, verbose_name='Listing Status')),
                ('iQuantitySold', models.SmallIntegerField(verbose_name='quantity sold')),
                ('cShipToLocations', models.CharField(max_length=188, verbose_name='ship to locations')),
                ('cSite', models.CharField(max_length=8, verbose_name='Site')),
                ('cTimeLeft', models.CharField(max_length=18, verbose_name='time left')),
                ('cTitle', models.CharField(max_length=80, verbose_name='item title')),
                ('iHitCount', models.SmallIntegerField(verbose_name='Hit Count')),
                ('cCategoryPath', models.CharField(max_length=48, verbose_name='category path')),
                ('cCountry', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('cReturnPolicy', models.CharField(max_length=48, verbose_name='Return Policy')),
                ('dMinimumBid', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Minimum Bid')),
                ('cBidCurrency', models.CharField(default='USD', max_length=3, verbose_name='bid currency')),
                ('iConditionID', models.SmallIntegerField(blank=True, null=True, verbose_name='Condition ID')),
                ('cCondition', models.CharField(blank=True, max_length=28, null=True, verbose_name='condition display name')),
                ('bGlobalShipping', models.BooleanField(default=False, verbose_name='Global Shipping')),
                ('tCreate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created on')),
            ],
            options={
                'verbose_name_plural': 'items',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('iItemNumb', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ebay item number')),
                ('isequence', models.PositiveSmallIntegerField(verbose_name='sequence')),
                ('cfilename', models.CharField(max_length=28, verbose_name='local file name')),
                ('coriginalurl', models.TextField(verbose_name='original URL')),
                ('tCreate', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('iUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name_plural': 'itemimages',
                'db_table': 'itemimages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemimage',
            unique_together=set([('iItemNumb', 'isequence')]),
        ),
    ]
