# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0003_auto_20180426_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dConvertCurrency',
            new_name='cConvertCurrency',
        ),
        migrations.AddField(
            model_name='item',
            name='cBuyItNowConvert',
            field=models.CharField(default='USD', max_length=3, verbose_name='buy it now local currency converted to this'),
        ),
        migrations.AddField(
            model_name='item',
            name='dBuyItNowPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='buy it now price (converted)'),
        ),
        migrations.AddField(
            model_name='item',
            name='lBuyItNowCurrenc',
            field=models.CharField(default='USD', max_length=3, verbose_name='buy it now local currency'),
        ),
        migrations.AddField(
            model_name='item',
            name='lBuyItNowPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='buy it now price (local currency)'),
        ),
        migrations.AddField(
            model_name='item',
            name='tModify',
            field=models.DateTimeField(null=True, verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cHighBidder',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='high bidder user name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dMinimumBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Minimum Bid'),
        ),
        migrations.AlterField(
            model_name='item',
            name='iCategoryID',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='primary category ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lLocalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price (local currency)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tCreate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
    ]
