# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0004_auto_20180428_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cCategoryPath',
        ),
        migrations.AddField(
            model_name='item',
            name='cCategoryIDs',
            field=models.CharField(default='abc', max_length=88, verbose_name='category IDs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='cCategoryNames',
            field=models.CharField(default='bcd', max_length=148, verbose_name='category names'),
            preserve_default=False,
        ),
    ]
