# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0009_auto_20180605_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iFeedbackScore',
            field=models.BigIntegerField(verbose_name='seller feedback score'),
        ),
    ]
