# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0010_auto_20180610_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cDescription',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
