# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0014_item_igotpictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iGotPictures',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='how many pictures downloaded'),
        ),
    ]
