# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0015_auto_20180702_0115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Keeper',
        ),
        migrations.RenameModel(
            old_name='ItemImage',
            new_name='KeeperImage',
        ),
        migrations.AlterModelOptions(
            name='keeper',
            options={'verbose_name_plural': 'keepers'},
        ),
        migrations.AlterModelOptions(
            name='keeperimage',
            options={'verbose_name_plural': 'keeperimages'},
        ),
        migrations.AlterModelTable(
            name='keeper',
            table='keepers',
        ),
        migrations.AlterModelTable(
            name='keeperimage',
            table='keeperimages',
        ),
    ]
