# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0016_auto_20180916_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeper',
            name='cPaymentMethods',
            field=models.CharField(blank=True, max_length=88, null=True, verbose_name='ebay item URL'),
        ),
    ]
