# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0018_auto_20190126_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeper',
            name='bBuyItNowable',
            field=models.NullBooleanField(default=False, verbose_name='buy it now enabled?'),
        ),
    ]
