# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0019_auto_20190227_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keeper',
            name='cCategory',
        ),
        migrations.RemoveField(
            model_name='keeper',
            name='cTimeLeft',
        ),
        migrations.AlterField(
            model_name='keeper',
            name='cPaymentMethods',
            field=models.CharField(blank=True, max_length=88, null=True, verbose_name='Payment methods'),
        ),
    ]
