# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0023_auto_20190620_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkeeper',
            name='bListExclude',
        ),
    ]
