# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0025_remove_userkeeper_tgotpics'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeper',
            name='tRetrieveFinal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retrieved info after end'),
        ),
        migrations.AddField(
            model_name='keeper',
            name='tRetrieved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retrieved info'),
        ),
    ]
