# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-31 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0027_auto_20190628_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeeper',
            name='iItemNumb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepers.Keeper'),
        ),
    ]
