# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0028_auto_20190831_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeper',
            name='bDeleteMaybe',
            field=models.BooleanField(default=False, verbose_name='delete later if nobody wants'),
        ),
    ]
