# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-22 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0031_auto_20200315_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeper',
            name='tGotPictures',
            field=models.DateTimeField(null=True, verbose_name='tried to download pictures'),
        ),
        migrations.AlterField(
            model_name='userkeeper',
            name='bGetPictures',
            field=models.BooleanField(default=False, help_text='By default, Bot will download pictures for auctions with at least one bid.  If this is a zero bid auction and you want pictures anyway, chick on this (reminder pics are big and storage space costs $).', verbose_name='Want to download pictures for this?'),
        ),
    ]
