# Generated by Django 2.2.10 on 2020-05-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0032_auto_20200322_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeper',
            name='cLocation',
            field=models.CharField(max_length=58, verbose_name='location'),
        ),
    ]
