# Generated by Django 2.2.13 on 2020-08-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0033_auto_20200503_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeper',
            name='tTimeBeg',
            field=models.DateTimeField(null=True, verbose_name='began'),
        ),
        migrations.AlterField(
            model_name='keeper',
            name='tTimeEnd',
            field=models.DateTimeField(null=True, verbose_name='end'),
        ),
    ]
