# Generated by Django 3.1.4 on 2020-12-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepers', '0034_auto_20200809_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeper',
            name='bBuyItNowable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='buy it now enabled?'),
        ),
    ]
